<?php

/**
 * This is the model base class for the table "meal_cutoffs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MealCutoffs".
 *
 * Columns in table "meal_cutoffs" available as properties of the model,
 * followed by relations of table "meal_cutoffs" available as properties of the model.
 *
 * @property string $id
 * @property string $meal_id
 * @property string $attendee_id
 * @property integer $is_cutoff
 * @property string $reason
 * @property string $reported_by
 * @property string $reported_at
 * @property string $approved_by
 * @property string $approved_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property Meals $meal
 */
abstract class BaseMealCutoffs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'meal_cutoffs';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MealCutoffs|MealCutoffs', $n);
	}

	public static function representingColumn() {
		return 'reason';
	}

	public function rules() {
		return array(
			array('meal_id, attendee_id, reported_by', 'required'),
			array('is_cutoff', 'numerical', 'integerOnly'=>true),
			array('meal_id, attendee_id, reported_by, approved_by', 'length', 'max'=>20),
			array('reason', 'length', 'max'=>255),
			array('reported_at, approved_at, created_at, updated_at, deleted_at', 'safe'),
			array('is_cutoff, reason, reported_at, approved_by, approved_at, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, meal_id, attendee_id, is_cutoff, reason, reported_by, reported_at, approved_by, approved_at, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'meal' => array(self::BELONGS_TO, 'Meals', 'meal_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'meal_id' => null,
			'attendee_id' => null,
			'is_cutoff' => Yii::t('app', 'Is Cutoff'),
			'reason' => Yii::t('app', 'Reason'),
			'reported_by' => Yii::t('app', 'Reported By'),
			'reported_at' => Yii::t('app', 'Reported At'),
			'approved_by' => Yii::t('app', 'Approved By'),
			'approved_at' => Yii::t('app', 'Approved At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'meal' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('meal_id', $this->meal_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('is_cutoff', $this->is_cutoff);
		$criteria->compare('reason', $this->reason, true);
		$criteria->compare('reported_by', $this->reported_by, true);
		$criteria->compare('reported_at', $this->reported_at, true);
		$criteria->compare('approved_by', $this->approved_by, true);
		$criteria->compare('approved_at', $this->approved_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}