<?php

/**
 * This is the model base class for the table "event_competitions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventCompetitions".
 *
 * Columns in table "event_competitions" available as properties of the model,
 * followed by relations of table "event_competitions" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $competition_id
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Competitions $competition
 * @property Events $event
 */
abstract class BaseEventCompetitions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'event_competitions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EventCompetitions|EventCompetitions', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('event_id, competition_id', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('event_id, competition_id', 'length', 'max'=>20),
			array('created_at, updated_at, deleted_at', 'safe'),
			array('status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, competition_id, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'competition' => array(self::BELONGS_TO, 'Competitions', 'competition_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'competition_id' => null,
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'competition' => null,
			'event' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('competition_id', $this->competition_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}