<?php

/**
 * This is the model base class for the table "beauty_round_results".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BeautyRoundResults".
 *
 * Columns in table "beauty_round_results" available as properties of the model,
 * followed by relations of table "beauty_round_results" available as properties of the model.
 *
 * @property string $id
 * @property string $registration_id
 * @property string $round_id
 * @property string $score
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property BeautyRegistrations $registration
 * @property BeautyRounds $round
 */
abstract class BaseBeautyRoundResults extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'beauty_round_results';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BeautyRoundResults|BeautyRoundResults', $n);
	}

	public static function representingColumn() {
		return 'score';
	}

	public function rules() {
		return array(
			array('registration_id, round_id', 'required'),
			array('registration_id, round_id', 'length', 'max'=>20),
			array('score', 'length', 'max'=>8),
			array('note, created_at, updated_at, deleted_at', 'safe'),
			array('score, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, registration_id, round_id, score, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'registration' => array(self::BELONGS_TO, 'BeautyRegistrations', 'registration_id'),
			'round' => array(self::BELONGS_TO, 'BeautyRounds', 'round_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'registration_id' => null,
			'round_id' => null,
			'score' => Yii::t('app', 'Score'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'registration' => null,
			'round' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('registration_id', $this->registration_id);
		$criteria->compare('round_id', $this->round_id);
		$criteria->compare('score', $this->score, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}