<?php

/**
 * This is the model base class for the table "sport_stages".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportStages".
 *
 * Columns in table "sport_stages" available as properties of the model,
 * followed by relations of table "sport_stages" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $sport_id
 * @property string $name
 * @property string $stage_type
 * @property integer $stage_order
 * @property string $start_date
 * @property string $end_date
 * @property string $location
 * @property string $rules
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property SportMatches[] $sportMatches
 * @property SportStageTeams[] $sportStageTeams
 * @property SportStageTeams[] $sportStageTeams1
 * @property Events $event
 * @property Sports $sport
 */
abstract class BaseSportStages extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_stages';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportStages|SportStages', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('sport_id, name', 'required'),
			array('stage_order', 'numerical', 'integerOnly'=>true),
			array('event_id, sport_id', 'length', 'max'=>20),
			array('name', 'length', 'max'=>100),
			array('stage_type', 'length', 'max'=>13),
			array('location', 'length', 'max'=>255),
			array('status', 'length', 'max'=>9),
			array('start_date, end_date, rules, created_at, updated_at, deleted_at', 'safe'),
			array('event_id, stage_type, stage_order, start_date, end_date, location, rules, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, sport_id, name, stage_type, stage_order, start_date, end_date, location, rules, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sportMatches' => array(self::HAS_MANY, 'SportMatches', 'stage_id'),
			'sportStageTeams' => array(self::HAS_MANY, 'SportStageTeams', 'qualified_from'),
			'sportStageTeams1' => array(self::HAS_MANY, 'SportStageTeams', 'stage_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'sport' => array(self::BELONGS_TO, 'Sports', 'sport_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'sport_id' => null,
			'name' => Yii::t('app', 'Name'),
			'stage_type' => Yii::t('app', 'Stage Type'),
			'stage_order' => Yii::t('app', 'Stage Order'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'location' => Yii::t('app', 'Location'),
			'rules' => Yii::t('app', 'Rules'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'sportMatches' => null,
			'sportStageTeams' => null,
			'sportStageTeams1' => null,
			'event' => null,
			'sport' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('sport_id', $this->sport_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('stage_type', $this->stage_type, true);
		$criteria->compare('stage_order', $this->stage_order);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('rules', $this->rules, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}