<?php

/**
 * This is the model base class for the table "sport_match_results".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportMatchResults".
 *
 * Columns in table "sport_match_results" available as properties of the model,
 * followed by relations of table "sport_match_results" available as properties of the model.
 *
 * @property string $id
 * @property string $match_id
 * @property string $score_a
 * @property string $score_b
 * @property string $winner_team_id
 * @property integer $is_draw
 * @property string $detail
 * @property string $note
 * @property integer $status
 * @property string $recorded_by
 * @property string $recorded_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property SportMatches $match
 * @property SportTeams $winnerTeam
 */
abstract class BaseSportMatchResults extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_match_results';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportMatchResults|SportMatchResults', $n);
	}

	public static function representingColumn() {
		return 'score_a';
	}

	public function rules() {
		return array(
			array('match_id', 'required'),
			array('is_draw, status', 'numerical', 'integerOnly'=>true),
			array('match_id, score_a, score_b, winner_team_id, recorded_by', 'length', 'max'=>20),
			array('detail, note, recorded_at, created_at, updated_at, deleted_at', 'safe'),
			array('score_a, score_b, winner_team_id, is_draw, detail, note, status, recorded_by, recorded_at, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, match_id, score_a, score_b, winner_team_id, is_draw, detail, note, status, recorded_by, recorded_at, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'match' => array(self::BELONGS_TO, 'SportMatches', 'match_id'),
			'winnerTeam' => array(self::BELONGS_TO, 'SportTeams', 'winner_team_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'match_id' => null,
			'score_a' => Yii::t('app', 'Score A'),
			'score_b' => Yii::t('app', 'Score B'),
			'winner_team_id' => null,
			'is_draw' => Yii::t('app', 'Is Draw'),
			'detail' => Yii::t('app', 'Detail'),
			'note' => Yii::t('app', 'Note'),
			'status' => Yii::t('app', 'Status'),
			'recorded_by' => Yii::t('app', 'Recorded By'),
			'recorded_at' => Yii::t('app', 'Recorded At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'match' => null,
			'winnerTeam' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('match_id', $this->match_id);
		$criteria->compare('score_a', $this->score_a, true);
		$criteria->compare('score_b', $this->score_b, true);
		$criteria->compare('winner_team_id', $this->winner_team_id);
		$criteria->compare('is_draw', $this->is_draw);
		$criteria->compare('detail', $this->detail, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('recorded_by', $this->recorded_by, true);
		$criteria->compare('recorded_at', $this->recorded_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}