<?php

/**
 * This is the model base class for the table "banquet_events".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BanquetEvents".
 *
 * Columns in table "banquet_events" available as properties of the model,
 * followed by relations of table "banquet_events" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $event_time
 * @property string $location
 * @property integer $total_tables
 * @property integer $seats_per_table
 * @property string $layout_description
 * @property string $layout_image_path
 * @property integer $canvas_width
 * @property integer $canvas_height
 * @property integer $is_active
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property BanquetTables[] $banquetTables
 */
abstract class BaseBanquetEvents extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banquet_events';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BanquetEvents|BanquetEvents', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, event_time, total_tables, seats_per_table, canvas_width, canvas_height', 'required'),
			array('total_tables, seats_per_table, canvas_width, canvas_height, is_active', 'numerical', 'integerOnly'=>true),
			array('name, location', 'length', 'max'=>255),
			array('layout_image_path', 'length', 'max'=>500),
			array('layout_description, created_at, updated_at, deleted_at', 'safe'),
			array('location, layout_description, layout_image_path, is_active, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, event_time, location, total_tables, seats_per_table, layout_description, layout_image_path, canvas_width, canvas_height, is_active, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'banquetTables' => array(self::HAS_MANY, 'BanquetTables', 'event_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'event_time' => Yii::t('app', 'Event Time'),
			'location' => Yii::t('app', 'Location'),
			'total_tables' => Yii::t('app', 'Total Tables'),
			'seats_per_table' => Yii::t('app', 'Seats Per Table'),
			'layout_description' => Yii::t('app', 'Layout Description'),
			'layout_image_path' => Yii::t('app', 'Layout Image Path'),
			'canvas_width' => Yii::t('app', 'Canvas Width'),
			'canvas_height' => Yii::t('app', 'Canvas Height'),
			'is_active' => Yii::t('app', 'Is Active'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'banquetTables' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('event_time', $this->event_time, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('total_tables', $this->total_tables);
		$criteria->compare('seats_per_table', $this->seats_per_table);
		$criteria->compare('layout_description', $this->layout_description, true);
		$criteria->compare('layout_image_path', $this->layout_image_path, true);
		$criteria->compare('canvas_width', $this->canvas_width);
		$criteria->compare('canvas_height', $this->canvas_height);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}