<?php

/**
 * This is the model base class for the table "sport_stage_teams".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportStageTeams".
 *
 * Columns in table "sport_stage_teams" available as properties of the model,
 * followed by relations of table "sport_stage_teams" available as properties of the model.
 *
 * @property string $id
 * @property string $stage_id
 * @property string $team_id
 * @property string $entry_type
 * @property string $qualified_from
 * @property integer $seed
 * @property integer $final_rank
 * @property string $status
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property SportStages $qualifiedFrom
 * @property SportStages $stage
 * @property SportTeams $team
 */
abstract class BaseSportStageTeams extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_stage_teams';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportStageTeams|SportStageTeams', $n);
	}

	public static function representingColumn() {
		return 'entry_type';
	}

	public function rules() {
		return array(
			array('stage_id, team_id', 'required'),
			array('seed, final_rank', 'numerical', 'integerOnly'=>true),
			array('stage_id, team_id, qualified_from', 'length', 'max'=>20),
			array('entry_type', 'length', 'max'=>14),
			array('status', 'length', 'max'=>10),
			array('note, created_at, updated_at, deleted_at', 'safe'),
			array('entry_type, qualified_from, seed, final_rank, status, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, stage_id, team_id, entry_type, qualified_from, seed, final_rank, status, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'qualifiedFrom' => array(self::BELONGS_TO, 'SportStages', 'qualified_from'),
			'stage' => array(self::BELONGS_TO, 'SportStages', 'stage_id'),
			'team' => array(self::BELONGS_TO, 'SportTeams', 'team_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'stage_id' => null,
			'team_id' => null,
			'entry_type' => Yii::t('app', 'Entry Type'),
			'qualified_from' => null,
			'seed' => Yii::t('app', 'Seed'),
			'final_rank' => Yii::t('app', 'Final Rank'),
			'status' => Yii::t('app', 'Status'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'qualifiedFrom' => null,
			'stage' => null,
			'team' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('stage_id', $this->stage_id);
		$criteria->compare('team_id', $this->team_id);
		$criteria->compare('entry_type', $this->entry_type, true);
		$criteria->compare('qualified_from', $this->qualified_from);
		$criteria->compare('seed', $this->seed);
		$criteria->compare('final_rank', $this->final_rank);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}