<?php

/**
 * This is the model base class for the table "beauty_registrations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BeautyRegistrations".
 *
 * Columns in table "beauty_registrations" available as properties of the model,
 * followed by relations of table "beauty_registrations" available as properties of the model.
 *
 * @property string $id
 * @property string $competition_id
 * @property string $attendee_id
 * @property string $candidate_number
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property BeautyCompetitions $competition
 * @property BeautyRoundResults[] $beautyRoundResults
 */
abstract class BaseBeautyRegistrations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'beauty_registrations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BeautyRegistrations|BeautyRegistrations', $n);
	}

	public static function representingColumn() {
		return 'candidate_number';
	}

	public function rules() {
		return array(
			array('competition_id, attendee_id', 'required'),
			array('competition_id, attendee_id, candidate_number', 'length', 'max'=>20),
			array('created_at, updated_at, deleted_at', 'safe'),
			array('candidate_number, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, competition_id, attendee_id, candidate_number, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'competition' => array(self::BELONGS_TO, 'BeautyCompetitions', 'competition_id'),
			'beautyRoundResults' => array(self::HAS_MANY, 'BeautyRoundResults', 'registration_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'competition_id' => null,
			'attendee_id' => null,
			'candidate_number' => Yii::t('app', 'Candidate Number'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'competition' => null,
			'beautyRoundResults' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('competition_id', $this->competition_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('candidate_number', $this->candidate_number, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}