<?php

/**
 * This is the model base class for the table "audit_logs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AuditLogs".
 *
 * Columns in table "audit_logs" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $user_id
 * @property string $module
 * @property string $action
 * @property string $target_table
 * @property string $target_id
 * @property string $old_values
 * @property string $new_values
 * @property string $ip_address
 * @property string $user_agent
 * @property string $created_at
 *
 */
abstract class BaseAuditLogs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'audit_logs';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AuditLogs|AuditLogs', $n);
	}

	public static function representingColumn() {
		return 'module';
	}

	public function rules() {
		return array(
			array('module, action', 'required'),
			array('user_id, target_id', 'length', 'max'=>20),
			array('module, action', 'length', 'max'=>50),
			array('target_table', 'length', 'max'=>100),
			array('ip_address', 'length', 'max'=>45),
			array('user_agent', 'length', 'max'=>255),
			array('created_at', 'length', 'max'=>10),
			array('old_values, new_values', 'safe'),
			array('user_id, target_table, target_id, old_values, new_values, ip_address, user_agent, created_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, module, action, target_table, target_id, old_values, new_values, ip_address, user_agent, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'module' => Yii::t('app', 'Module'),
			'action' => Yii::t('app', 'Action'),
			'target_table' => Yii::t('app', 'Target Table'),
			'target_id' => Yii::t('app', 'Target'),
			'old_values' => Yii::t('app', 'Old Values'),
			'new_values' => Yii::t('app', 'New Values'),
			'ip_address' => Yii::t('app', 'Ip Address'),
			'user_agent' => Yii::t('app', 'User Agent'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('module', $this->module, true);
		$criteria->compare('action', $this->action, true);
		$criteria->compare('target_table', $this->target_table, true);
		$criteria->compare('target_id', $this->target_id, true);
		$criteria->compare('old_values', $this->old_values, true);
		$criteria->compare('new_values', $this->new_values, true);
		$criteria->compare('ip_address', $this->ip_address, true);
		$criteria->compare('user_agent', $this->user_agent, true);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}