<?php

/**
 * This is the model base class for the table "attendees".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Attendees".
 *
 * Columns in table "attendees" available as properties of the model,
 * followed by relations of table "attendees" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $registration_id
 * @property string $property_id
 * @property string $staff_id
 * @property string $role_id
 * @property string $full_name
 * @property string $position
 * @property string $unit_label
 * @property string $photo_path
 * @property string $photo_full_path
 * @property string $qr_token
 * @property string $badge_number
 * @property integer $badge_generated
 * @property integer $badge_printed
 * @property string $transport_id
 * @property string $check_in_date
 * @property string $check_out_date
 * @property integer $is_team_lead
 * @property integer $is_active
 * @property integer $sort_order
 * @property string $approved_by
 * @property string $approved_at
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property AttendeeRoles[] $attendeeRoles
 * @property Events $event
 * @property Properties $property
 * @property Registrations $registration
 * @property Roles $role
 * @property Staffs $staff
 * @property Transports $transport
 * @property Badges[] $badges
 * @property BanquetSeats[] $banquetSeats
 * @property BeautyContestants[] $beautyContestants
 * @property BeautyRegistrations[] $beautyRegistrations
 * @property CompetitionRegistrations[] $competitionRegistrations
 * @property MealAttendees[] $mealAttendees
 * @property MealCheckins[] $mealCheckins
 * @property MealCutoffs[] $mealCutoffs
 * @property MealRestrictions[] $mealRestrictions
 * @property MealVouchers[] $mealVouchers
 * @property SportTeamMembers[] $sportTeamMembers
 * @property TalentEntryMembers[] $talentEntryMembers
 */
abstract class BaseAttendees extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'attendees';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Attendees|Attendees', $n);
	}

	public static function representingColumn() {
		return 'full_name';
	}

	public function rules() {
		return array(
			array('registration_id, property_id, full_name', 'required'),
			array('badge_generated, badge_printed, is_team_lead, is_active, sort_order', 'numerical', 'integerOnly'=>true),
			array('event_id, registration_id, property_id, staff_id, role_id, badge_number, transport_id, approved_by, approved_at', 'length', 'max'=>20),
			array('full_name, position, unit_label', 'length', 'max'=>255),
			array('photo_path, photo_full_path', 'length', 'max'=>500),
			array('qr_token', 'length', 'max'=>64),
			array('check_in_date, check_out_date, note, created_at, updated_at, deleted_at', 'safe'),
			array('event_id, staff_id, role_id, position, unit_label, photo_path, photo_full_path, qr_token, badge_number, badge_generated, badge_printed, transport_id, check_in_date, check_out_date, is_team_lead, is_active, sort_order, approved_by, approved_at, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, registration_id, property_id, staff_id, role_id, full_name, position, unit_label, photo_path, photo_full_path, qr_token, badge_number, badge_generated, badge_printed, transport_id, check_in_date, check_out_date, is_team_lead, is_active, sort_order, approved_by, approved_at, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendeeRoles' => array(self::HAS_MANY, 'AttendeeRoles', 'attendee_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'property' => array(self::BELONGS_TO, 'Properties', 'property_id'),
			'registration' => array(self::BELONGS_TO, 'Registrations', 'registration_id'),
			'role' => array(self::BELONGS_TO, 'Roles', 'role_id'),
			'staff' => array(self::BELONGS_TO, 'Staffs', 'staff_id'),
			'transport' => array(self::BELONGS_TO, 'Transports', 'transport_id'),
			'badges' => array(self::HAS_MANY, 'Badges', 'attendee_id'),
			'banquetSeats' => array(self::HAS_MANY, 'BanquetSeats', 'attendee_id'),
			'beautyContestants' => array(self::HAS_MANY, 'BeautyContestants', 'attendee_id'),
			'beautyRegistrations' => array(self::HAS_MANY, 'BeautyRegistrations', 'attendee_id'),
			'competitionRegistrations' => array(self::HAS_MANY, 'CompetitionRegistrations', 'attendee_id'),
			'mealAttendees' => array(self::HAS_MANY, 'MealAttendees', 'attendee_id'),
			'mealCheckins' => array(self::HAS_MANY, 'MealCheckins', 'attendee_id'),
			'mealCutoffs' => array(self::HAS_MANY, 'MealCutoffs', 'attendee_id'),
			'mealRestrictions' => array(self::HAS_MANY, 'MealRestrictions', 'attendee_id'),
			'mealVouchers' => array(self::HAS_MANY, 'MealVouchers', 'attendee_id'),
			'sportTeamMembers' => array(self::HAS_MANY, 'SportTeamMembers', 'attendee_id'),
			'talentEntryMembers' => array(self::HAS_MANY, 'TalentEntryMembers', 'attendee_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'registration_id' => null,
			'property_id' => null,
			'staff_id' => null,
			'role_id' => null,
			'full_name' => Yii::t('app', 'Full Name'),
			'position' => Yii::t('app', 'Position'),
			'unit_label' => Yii::t('app', 'Unit Label'),
			'photo_path' => Yii::t('app', 'Photo Path'),
			'photo_full_path' => Yii::t('app', 'Photo Full Path'),
			'qr_token' => Yii::t('app', 'Qr Token'),
			'badge_number' => Yii::t('app', 'Badge Number'),
			'badge_generated' => Yii::t('app', 'Badge Generated'),
			'badge_printed' => Yii::t('app', 'Badge Printed'),
			'transport_id' => null,
			'check_in_date' => Yii::t('app', 'Check In Date'),
			'check_out_date' => Yii::t('app', 'Check Out Date'),
			'is_team_lead' => Yii::t('app', 'Is Team Lead'),
			'is_active' => Yii::t('app', 'Is Active'),
			'sort_order' => Yii::t('app', 'Sort Order'),
			'approved_by' => Yii::t('app', 'Approved By'),
			'approved_at' => Yii::t('app', 'Approved At'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendeeRoles' => null,
			'event' => null,
			'property' => null,
			'registration' => null,
			'role' => null,
			'staff' => null,
			'transport' => null,
			'badges' => null,
			'banquetSeats' => null,
			'beautyContestants' => null,
			'beautyRegistrations' => null,
			'competitionRegistrations' => null,
			'mealAttendees' => null,
			'mealCheckins' => null,
			'mealCutoffs' => null,
			'mealRestrictions' => null,
			'mealVouchers' => null,
			'sportTeamMembers' => null,
			'talentEntryMembers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('registration_id', $this->registration_id);
		$criteria->compare('property_id', $this->property_id);
		$criteria->compare('staff_id', $this->staff_id);
		$criteria->compare('role_id', $this->role_id);
		$criteria->compare('full_name', $this->full_name, true);
		$criteria->compare('position', $this->position, true);
		$criteria->compare('unit_label', $this->unit_label, true);
		$criteria->compare('photo_path', $this->photo_path, true);
		$criteria->compare('photo_full_path', $this->photo_full_path, true);
		$criteria->compare('qr_token', $this->qr_token, true);
		$criteria->compare('badge_number', $this->badge_number, true);
		$criteria->compare('badge_generated', $this->badge_generated);
		$criteria->compare('badge_printed', $this->badge_printed);
		$criteria->compare('transport_id', $this->transport_id);
		$criteria->compare('check_in_date', $this->check_in_date, true);
		$criteria->compare('check_out_date', $this->check_out_date, true);
		$criteria->compare('is_team_lead', $this->is_team_lead);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('sort_order', $this->sort_order);
		$criteria->compare('approved_by', $this->approved_by, true);
		$criteria->compare('approved_at', $this->approved_at, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}