<?php

/**
 * This is the model base class for the table "sport_standings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportStandings".
 *
 * Columns in table "sport_standings" available as properties of the model,
 * followed by relations of table "sport_standings" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $sport_id
 * @property string $team_id
 * @property integer $played
 * @property integer $won
 * @property integer $drawn
 * @property integer $lost
 * @property integer $goals_for
 * @property integer $goals_against
 * @property integer $points
 * @property integer $rank
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Events $event
 * @property Sports $sport
 * @property SportTeams $team
 */
abstract class BaseSportStandings extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_standings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportStandings|SportStandings', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('event_id, sport_id, team_id', 'required'),
			array('played, won, drawn, lost, goals_for, goals_against, points, rank', 'numerical', 'integerOnly'=>true),
			array('event_id, sport_id, team_id', 'length', 'max'=>20),
			array('created_at, updated_at, deleted_at', 'safe'),
			array('played, won, drawn, lost, goals_for, goals_against, points, rank, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, sport_id, team_id, played, won, drawn, lost, goals_for, goals_against, points, rank, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'sport' => array(self::BELONGS_TO, 'Sports', 'sport_id'),
			'team' => array(self::BELONGS_TO, 'SportTeams', 'team_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'sport_id' => null,
			'team_id' => null,
			'played' => Yii::t('app', 'Played'),
			'won' => Yii::t('app', 'Won'),
			'drawn' => Yii::t('app', 'Drawn'),
			'lost' => Yii::t('app', 'Lost'),
			'goals_for' => Yii::t('app', 'Goals For'),
			'goals_against' => Yii::t('app', 'Goals Against'),
			'points' => Yii::t('app', 'Points'),
			'rank' => Yii::t('app', 'Rank'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'event' => null,
			'sport' => null,
			'team' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('sport_id', $this->sport_id);
		$criteria->compare('team_id', $this->team_id);
		$criteria->compare('played', $this->played);
		$criteria->compare('won', $this->won);
		$criteria->compare('drawn', $this->drawn);
		$criteria->compare('lost', $this->lost);
		$criteria->compare('goals_for', $this->goals_for);
		$criteria->compare('goals_against', $this->goals_against);
		$criteria->compare('points', $this->points);
		$criteria->compare('rank', $this->rank);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}