<?php

/**
 * This is the model base class for the table "competition_round_results".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompetitionRoundResults".
 *
 * Columns in table "competition_round_results" available as properties of the model,
 * followed by relations of table "competition_round_results" available as properties of the model.
 *
 * @property string $id
 * @property string $round_id
 * @property string $registration_id
 * @property string $score
 * @property integer $rank
 * @property integer $passed
 * @property string $entry_type
 * @property string $note
 * @property string $scored_by
 * @property string $scored_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property CompetitionRegistrations $registration
 * @property CompetitionRounds $round
 */
abstract class BaseCompetitionRoundResults extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'competition_round_results';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompetitionRoundResults|CompetitionRoundResults', $n);
	}

	public static function representingColumn() {
		return 'entry_type';
	}

	public function rules() {
		return array(
			array('round_id, registration_id', 'required'),
			array('rank, passed', 'numerical', 'integerOnly'=>true),
			array('round_id, registration_id, scored_by', 'length', 'max'=>20),
			array('score', 'length', 'max'=>8),
			array('entry_type', 'length', 'max'=>13),
			array('note, scored_at, created_at, updated_at, deleted_at', 'safe'),
			array('score, rank, passed, entry_type, note, scored_by, scored_at, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, round_id, registration_id, score, rank, passed, entry_type, note, scored_by, scored_at, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'registration' => array(self::BELONGS_TO, 'CompetitionRegistrations', 'registration_id'),
			'round' => array(self::BELONGS_TO, 'CompetitionRounds', 'round_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'round_id' => null,
			'registration_id' => null,
			'score' => Yii::t('app', 'Score'),
			'rank' => Yii::t('app', 'Rank'),
			'passed' => Yii::t('app', 'Passed'),
			'entry_type' => Yii::t('app', 'Entry Type'),
			'note' => Yii::t('app', 'Note'),
			'scored_by' => Yii::t('app', 'Scored By'),
			'scored_at' => Yii::t('app', 'Scored At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'registration' => null,
			'round' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('round_id', $this->round_id);
		$criteria->compare('registration_id', $this->registration_id);
		$criteria->compare('score', $this->score, true);
		$criteria->compare('rank', $this->rank);
		$criteria->compare('passed', $this->passed);
		$criteria->compare('entry_type', $this->entry_type, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('scored_by', $this->scored_by, true);
		$criteria->compare('scored_at', $this->scored_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}