<?php

/**
 * This is the model base class for the table "m_roles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MRoles".
 *
 * Columns in table "m_roles" available as properties of the model,
 * followed by relations of table "m_roles" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $controllers
 *
 * @property MUsers[] $mUsers
 */
abstract class BaseMRoles extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'm_roles';
    }

    public static function representingColumn()
    {
        return 'title';
    }

    public function rules()
    {
        return array(
            array('title, controllers', 'required'),
            array('title, controllers,module_slug', 'length', 'max' => 255),
            array('id, title, controllers,module_slug', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'mUsers' => array(self::HAS_MANY, 'MUsers', 'role_id'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'controllers' => Yii::t('app', 'Controllers'),
            'is_hotel' => Yii::t('app', 'Đơn vị có thể tạo'),
            'mUsers' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('controllers', $this->controllers, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}