<?php

/**
 * This is the model base class for the table "beauty_contestants".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BeautyContestants".
 *
 * Columns in table "beauty_contestants" available as properties of the model,
 * followed by relations of table "beauty_contestants" available as properties of the model.
 *
 * @property string $id
 * @property string $contest_id
 * @property string $attendee_id
 * @property string $candidate_number
 * @property double $height_cm
 * @property double $weight_kg
 * @property string $measurements
 * @property string $talent
 * @property string $bio
 * @property string $photo_portrait
 * @property string $photo_full_body
 * @property string $award
 * @property integer $final_rank
 * @property string $registered_at
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property BeautyContests $contest
 * @property BeautyScores[] $beautyScores
 */
abstract class BaseBeautyContestants extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'beauty_contestants';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BeautyContestants|BeautyContestants', $n);
	}

	public static function representingColumn() {
		return 'candidate_number';
	}

	public function rules() {
		return array(
			array('contest_id, attendee_id, candidate_number', 'required'),
			array('final_rank', 'numerical', 'integerOnly'=>true),
			array('height_cm, weight_kg', 'numerical'),
			array('contest_id, attendee_id, candidate_number', 'length', 'max'=>20),
			array('measurements', 'length', 'max'=>50),
			array('talent, award', 'length', 'max'=>255),
			array('photo_portrait, photo_full_body', 'length', 'max'=>500),
			array('status', 'length', 'max'=>12),
			array('bio, registered_at, created_at, updated_at, deleted_at', 'safe'),
			array('height_cm, weight_kg, measurements, talent, bio, photo_portrait, photo_full_body, award, final_rank, registered_at, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, contest_id, attendee_id, candidate_number, height_cm, weight_kg, measurements, talent, bio, photo_portrait, photo_full_body, award, final_rank, registered_at, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'contest' => array(self::BELONGS_TO, 'BeautyContests', 'contest_id'),
			'beautyScores' => array(self::HAS_MANY, 'BeautyScores', 'contestant_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'contest_id' => null,
			'attendee_id' => null,
			'candidate_number' => Yii::t('app', 'Candidate Number'),
			'height_cm' => Yii::t('app', 'Height Cm'),
			'weight_kg' => Yii::t('app', 'Weight Kg'),
			'measurements' => Yii::t('app', 'Measurements'),
			'talent' => Yii::t('app', 'Talent'),
			'bio' => Yii::t('app', 'Bio'),
			'photo_portrait' => Yii::t('app', 'Photo Portrait'),
			'photo_full_body' => Yii::t('app', 'Photo Full Body'),
			'award' => Yii::t('app', 'Award'),
			'final_rank' => Yii::t('app', 'Final Rank'),
			'registered_at' => Yii::t('app', 'Registered At'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'contest' => null,
			'beautyScores' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('contest_id', $this->contest_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('candidate_number', $this->candidate_number, true);
		$criteria->compare('height_cm', $this->height_cm);
		$criteria->compare('weight_kg', $this->weight_kg);
		$criteria->compare('measurements', $this->measurements, true);
		$criteria->compare('talent', $this->talent, true);
		$criteria->compare('bio', $this->bio, true);
		$criteria->compare('photo_portrait', $this->photo_portrait, true);
		$criteria->compare('photo_full_body', $this->photo_full_body, true);
		$criteria->compare('award', $this->award, true);
		$criteria->compare('final_rank', $this->final_rank);
		$criteria->compare('registered_at', $this->registered_at, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}