<?php

/**
 * This is the model base class for the table "competitions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Competitions".
 *
 * Columns in table "competitions" available as properties of the model,
 * followed by relations of table "competitions" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 * @property string $registration_open_at
 * @property string $registration_close_at
 * @property string $candidate_number_prefix
 * @property integer $candidate_number_start
 * @property integer $candidate_number_pad
 * @property integer $max_per_org
 * @property integer $has_qualification
 * @property integer $allow_direct_final
 * @property integer $is_active
 * @property string $created_by
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property CompetitionRegistrations[] $competitionRegistrations
 * @property CompetitionRounds[] $competitionRounds
 * @property EventCompetitions[] $eventCompetitions
 * @property RegistrationDetails[] $registrationDetails
 */
abstract class BaseCompetitions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'competitions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Competitions|Competitions', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('candidate_number_start, candidate_number_pad, max_per_org, has_qualification, allow_direct_final, is_active', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('candidate_number_prefix', 'length', 'max'=>10),
			array('created_by', 'length', 'max'=>20),
			array('description, registration_open_at, registration_close_at, created_at, updated_at, deleted_at', 'safe'),
			array('description, registration_open_at, registration_close_at, candidate_number_prefix, candidate_number_start, candidate_number_pad, max_per_org, has_qualification, allow_direct_final, is_active, created_by, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, registration_open_at, registration_close_at, candidate_number_prefix, candidate_number_start, candidate_number_pad, max_per_org, has_qualification, allow_direct_final, is_active, created_by, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'competitionRegistrations' => array(self::HAS_MANY, 'CompetitionRegistrations', 'competition_id'),
			'competitionRounds' => array(self::HAS_MANY, 'CompetitionRounds', 'competition_id'),
			'eventCompetitions' => array(self::HAS_MANY, 'EventCompetitions', 'competition_id'),
			'registrationDetails' => array(self::HAS_MANY, 'RegistrationDetails', 'competition_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'registration_open_at' => Yii::t('app', 'Registration Open At'),
			'registration_close_at' => Yii::t('app', 'Registration Close At'),
			'candidate_number_prefix' => Yii::t('app', 'Candidate Number Prefix'),
			'candidate_number_start' => Yii::t('app', 'Candidate Number Start'),
			'candidate_number_pad' => Yii::t('app', 'Candidate Number Pad'),
			'max_per_org' => Yii::t('app', 'Max Per Org'),
			'has_qualification' => Yii::t('app', 'Has Qualification'),
			'allow_direct_final' => Yii::t('app', 'Allow Direct Final'),
			'is_active' => Yii::t('app', 'Is Active'),
			'created_by' => Yii::t('app', 'Created By'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'competitionRegistrations' => null,
			'competitionRounds' => null,
			'eventCompetitions' => null,
			'registrationDetails' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('registration_open_at', $this->registration_open_at, true);
		$criteria->compare('registration_close_at', $this->registration_close_at, true);
		$criteria->compare('candidate_number_prefix', $this->candidate_number_prefix, true);
		$criteria->compare('candidate_number_start', $this->candidate_number_start);
		$criteria->compare('candidate_number_pad', $this->candidate_number_pad);
		$criteria->compare('max_per_org', $this->max_per_org);
		$criteria->compare('has_qualification', $this->has_qualification);
		$criteria->compare('allow_direct_final', $this->allow_direct_final);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('created_by', $this->created_by, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}