<?php

/**
 * This is the model base class for the table "properties".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Properties".
 *
 * Columns in table "properties" available as properties of the model,
 * followed by relations of table "properties" available as properties of the model.
 *
 * @property string $id
 * @property string $prefix
 * @property string $code
 * @property string $smile_code
 * @property string $name
 * @property string $active_date
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees[] $attendees
 * @property EventUnits[] $eventUnits
 * @property Registrations[] $registrations
 * @property Registrations[] $registrations1
 * @property SportTeams[] $sportTeams
 * @property TalentEntries[] $talentEntries
 */
abstract class BaseProperties extends GxActiveRecord
{

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'properties';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'Đơn vị', $n);
	}

	public static function representingColumn()
	{
		return 'prefix';
	}

	public function rules()
	{
		return array(
			array('prefix, code, smile_code, name', 'required'),
			array('status', 'numerical', 'integerOnly' => true),
			array('prefix, code, smile_code', 'length', 'max' => 20),
			array('name', 'length', 'max' => 255),
			array('active_date, created_at, updated_at, deleted_at', 'safe'),
			array('active_date, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, prefix, code, smile_code, name, active_date, status, created_at, updated_at, deleted_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
			'attendees' => array(self::HAS_MANY, 'Attendees', 'property_id'),
			'eventUnits' => array(self::HAS_MANY, 'EventUnits', 'property_id'),
			'registrations' => array(self::HAS_MANY, 'Registrations', 'property_id'),
			'registrations1' => array(self::HAS_MANY, 'Registrations', 'relation_property_id'),
			'sportTeams' => array(self::HAS_MANY, 'SportTeams', 'property_id'),
			'talentEntries' => array(self::HAS_MANY, 'TalentEntries', 'property_id'),
		);
	}

	public function pivotModels()
	{
		return array();
	}

	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('app', 'ID'),
			'prefix' => Yii::t('app', 'Mã đơn vị'),
			'code' => Yii::t('app', 'Mã đơn vị'),
			'smile_code' => Yii::t('app', 'Mã Smile'),
			'name' => Yii::t('app', 'Tên đơn vị'),
			'active_date' => Yii::t('app', 'Ngày bắt đầu'),
			'status' => Yii::t('app', 'Trạng thái'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendees' => null,
			'eventUnits' => null,
			'registrations' => null,
			'registrations1' => null,
			'sportTeams' => null,
			'talentEntries' => null,
		);
	}

	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('prefix', $this->prefix, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('smile_code', $this->smile_code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active_date', $this->active_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
