<?php

/**
 * This is the model base class for the table "event_agenda".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventAgenda".
 *
 * Columns in table "event_agenda" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $title
 * @property string $description
 * @property string $location
 * @property string $start_time
 * @property string $end_time
 * @property string $type
 * @property integer $is_public
 * @property integer $sort_order
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 */
abstract class BaseEventAgenda extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'event_agenda';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EventAgenda|EventAgendas', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, start_time', 'required'),
			array('is_public, sort_order', 'numerical', 'integerOnly'=>true),
			array('title, location', 'length', 'max'=>255),
			array('type', 'length', 'max'=>8),
			array('description, end_time, created_at, updated_at, deleted_at', 'safe'),
			array('description, location, end_time, type, is_public, sort_order, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, description, location, start_time, end_time, type, is_public, sort_order, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'location' => Yii::t('app', 'Location'),
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
			'type' => Yii::t('app', 'Type'),
			'is_public' => Yii::t('app', 'Is Public'),
			'sort_order' => Yii::t('app', 'Sort Order'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('end_time', $this->end_time, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('is_public', $this->is_public);
		$criteria->compare('sort_order', $this->sort_order);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}