<?php

/**
 * This is the model base class for the table "talent_shows".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TalentShows".
 *
 * Columns in table "talent_shows" available as properties of the model,
 * followed by relations of table "talent_shows" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $name
 * @property string $description
 * @property string $registration_open_at
 * @property string $registration_close_at
 * @property string $show_date
 * @property string $location
 * @property integer $max_entries_per_org
 * @property integer $is_active
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property TalentEntries[] $talentEntries
 * @property Events $event
 */
abstract class BaseTalentShows extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'talent_shows';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TalentShows|TalentShows', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('event_id, name', 'required'),
			array('max_entries_per_org, is_active', 'numerical', 'integerOnly'=>true),
			array('event_id', 'length', 'max'=>20),
			array('name, location', 'length', 'max'=>255),
			array('description, registration_open_at, registration_close_at, show_date, created_at, updated_at, deleted_at', 'safe'),
			array('description, registration_open_at, registration_close_at, show_date, location, max_entries_per_org, is_active, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, name, description, registration_open_at, registration_close_at, show_date, location, max_entries_per_org, is_active, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'talentEntries' => array(self::HAS_MANY, 'TalentEntries', 'show_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'registration_open_at' => Yii::t('app', 'Registration Open At'),
			'registration_close_at' => Yii::t('app', 'Registration Close At'),
			'show_date' => Yii::t('app', 'Show Date'),
			'location' => Yii::t('app', 'Location'),
			'max_entries_per_org' => Yii::t('app', 'Max Entries Per Org'),
			'is_active' => Yii::t('app', 'Is Active'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'talentEntries' => null,
			'event' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('registration_open_at', $this->registration_open_at, true);
		$criteria->compare('registration_close_at', $this->registration_close_at, true);
		$criteria->compare('show_date', $this->show_date, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('max_entries_per_org', $this->max_entries_per_org);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}