<?php

/**
 * This is the model base class for the table "contents".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contents".
 *
 * Columns in table "contents" available as properties of the model,
 * followed by relations of table "contents" available as properties of the model.
 *
 * @property string $id
 * @property string $code
 * @property string $name
 * @property string $description
 * @property integer $status
 * @property integer $sort_order
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property EventContents[] $eventContents
 * @property RegistrationDetails[] $registrationDetails
 */
abstract class BaseContents extends GxActiveRecord
{

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'contents';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'Nội dung', $n);
	}

	public static function representingColumn()
	{
		return 'code';
	}

	public function rules()
	{
		return array(
			array('name', 'required'),
			array('status, sort_order', 'numerical', 'integerOnly' => true),
			array('name', 'length', 'max' => 255),
			array('description, created_at, updated_at, deleted_at', 'safe'),
			array('description, status, sort_order, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, description, status, sort_order, created_at, updated_at, deleted_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
			'eventContents' => array(self::HAS_MANY, 'EventContents', 'content_id'),
			'registrationDetails' => array(self::HAS_MANY, 'RegistrationDetails', 'content_id'),
		);
	}

	public function pivotModels()
	{
		return array();
	}

	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'status' => Yii::t('app', 'Status'),
			'sort_order' => Yii::t('app', 'Sort Order'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'eventContents' => null,
			'registrationDetails' => null,
		);
	}

	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('sort_order', $this->sort_order);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
