<?php

/**
 * This is the model base class for the table "sports".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sports".
 *
 * Columns in table "sports" available as properties of the model,
 * followed by relations of table "sports" available as properties of the model.
 *
 * @property string $id
 * @property string $code
 * @property string $name
 * @property string $parent_id
 * @property string $type
 * @property string $description
 * @property string $document
 * @property integer $is_active
 * @property integer $sort_order
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property EventSports[] $eventSports
 * @property RegistrationDetails[] $registrationDetails
 * @property SportMatches[] $sportMatches
 * @property SportStages[] $sportStages
 * @property SportStandings[] $sportStandings
 * @property SportTeams[] $sportTeams
 * @property Sports $parent
 * @property Sports[] $sports
 */
abstract class BaseSports extends GxActiveRecord
{

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'sports';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'Nội dung Thể thao', $n);
	}

	public static function representingColumn()
	{
		return 'name';
	}

	public function rules()
	{
		return array(
			array('name', 'required'),
			array('is_active, sort_order', 'numerical', 'integerOnly' => true),
			array('code', 'length', 'max' => 50),
			array('name', 'length', 'max' => 100),
			array('parent_id', 'length', 'max' => 20),
			array('type', 'length', 'max' => 10),
			array('document', 'length', 'max' => 500),
			array('description, created_at, updated_at, deleted_at', 'safe'),
			array('code, parent_id, type, description, document, is_active, sort_order, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, parent_id, type, description, document, is_active, sort_order, created_at, updated_at, deleted_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
			'eventSports' => array(self::HAS_MANY, 'EventSports', 'sport_id'),
			'registrationDetails' => array(self::HAS_MANY, 'RegistrationDetails', 'sport_id'),
			'sportMatches' => array(self::HAS_MANY, 'SportMatches', 'sport_id'),
			'sportStages' => array(self::HAS_MANY, 'SportStages', 'sport_id'),
			'sportStandings' => array(self::HAS_MANY, 'SportStandings', 'sport_id'),
			'sportTeams' => array(self::HAS_MANY, 'SportTeams', 'sport_id'),
			'parent' => array(self::BELONGS_TO, 'Sports', 'parent_id'),
			'sports' => array(self::HAS_MANY, 'Sports', 'parent_id'),
		);
	}

	public function pivotModels()
	{
		return array();
	}

	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'parent_id' =>  Yii::t('app', 'Parent'),
			'type' => Yii::t('app', 'Type'),
			'description' => Yii::t('app', 'Description'),
			'document' => Yii::t('app', 'Document'),
			'is_active' => Yii::t('app', 'Is Active'),
			'sort_order' => Yii::t('app', 'Sort Order'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'eventSports' => null,
			'registrationDetails' => null,
			'sportMatches' => null,
			'sportStages' => null,
			'sportStandings' => null,
			'sportTeams' => null,
			'parent' => null,
			'sports' => null,
		);
	}

	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('document', $this->document, true);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('sort_order', $this->sort_order);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
