<?php

/**
 * This is the model base class for the table "events".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Events".
 *
 * Columns in table "events" available as properties of the model,
 * followed by relations of table "events" available as properties of the model.
 *
 * @property string $id
 * @property string $code
 * @property string $name
 * @property string $from_date
 * @property string $to_date
 * @property string $description
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees[] $attendees
 * @property BeautyCompetitions[] $beautyCompetitions
 * @property BeautyContests[] $beautyContests
 * @property EventCompetitions[] $eventCompetitions
 * @property EventContents[] $eventContents
 * @property EventSports[] $eventSports
 * @property EventUnits[] $eventUnits
 * @property Meals[] $meals
 * @property RegistrationPeriods[] $registrationPeriods
 * @property Registrations[] $registrations
 * @property Roles[] $roles
 * @property SportMatches[] $sportMatches
 * @property SportStages[] $sportStages
 * @property SportStandings[] $sportStandings
 * @property SportTeams[] $sportTeams
 * @property TalentShows[] $talentShows
 */
abstract class BaseEvents extends GxActiveRecord
{

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'events';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'Sự kiện', $n);
	}

	public static function representingColumn()
	{
		return 'code';
	}

	public function rules()
	{
		return array(
			array('name, from_date, to_date', 'required'),
			array('code', 'length', 'max' => 50),
			array('name', 'length', 'max' => 255),
			array('status', 'length', 'max' => 9),
			array('description, created_at, updated_at, deleted_at', 'safe'),
			array('description, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, from_date, to_date, description, status, created_at, updated_at, deleted_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
			'attendees' => array(self::HAS_MANY, 'Attendees', 'event_id'),
			'beautyCompetitions' => array(self::HAS_MANY, 'BeautyCompetitions', 'event_id'),
			'beautyContests' => array(self::HAS_MANY, 'BeautyContests', 'event_id'),
			'eventCompetitions' => array(self::HAS_MANY, 'EventCompetitions', 'event_id'),
			'eventContents' => array(self::HAS_MANY, 'EventContents', 'event_id'),
			'eventSports' => array(self::HAS_MANY, 'EventSports', 'event_id'),
			'eventUnits' => array(self::HAS_MANY, 'EventUnits', 'event_id'),
			'meals' => array(self::HAS_MANY, 'Meals', 'event_id'),
			'registrationPeriods' => array(self::HAS_MANY, 'RegistrationPeriods', 'event_id'),
			'registrations' => array(self::HAS_MANY, 'Registrations', 'event_id'),
			'roles' => array(self::HAS_MANY, 'Roles', 'event_id'),
			'sportMatches' => array(self::HAS_MANY, 'SportMatches', 'event_id'),
			'sportStages' => array(self::HAS_MANY, 'SportStages', 'event_id'),
			'sportStandings' => array(self::HAS_MANY, 'SportStandings', 'event_id'),
			'sportTeams' => array(self::HAS_MANY, 'SportTeams', 'event_id'),
			'talentShows' => array(self::HAS_MANY, 'TalentShows', 'event_id'),
		);
	}

	public function pivotModels()
	{
		return array();
	}

	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'from_date' => Yii::t('app', 'From Date'),
			'to_date' => Yii::t('app', 'To Date'),
			'description' => Yii::t('app', 'Description'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendees' => null,
			'beautyCompetitions' => null,
			'beautyContests' => null,
			'eventCompetitions' => null,
			'eventContents' => null,
			'eventSports' => null,
			'eventUnits' => null,
			'meals' => null,
			'registrationPeriods' => null,
			'registrations' => null,
			'roles' => null,
			'sportMatches' => null,
			'sportStages' => null,
			'sportStandings' => null,
			'sportTeams' => null,
			'talentShows' => null,
		);
	}

	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('from_date', $this->from_date, true);
		$criteria->compare('to_date', $this->to_date, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
