<?php

/**
 * This is the model base class for the table "registration_periods".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RegistrationPeriods".
 *
 * Columns in table "registration_periods" available as properties of the model,
 * followed by relations of table "registration_periods" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $name
 * @property string $start_time
 * @property string $end_time
 * @property integer $max_per_org
 * @property integer $is_active
 * @property integer $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Events $event
 * @property Registrations[] $registrations
 */
abstract class BaseRegistrationPeriods extends GxActiveRecord
{

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'registration_periods';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'RegistrationPeriods|RegistrationPeriods', $n);
	}

	public static function representingColumn()
	{
		return 'name';
	}

	public function rules()
	{
		return array(
			array('event_id, name, start_time, end_time', 'required'),
			array('max_per_org, note', 'numerical', 'integerOnly' => true),
			array('event_id', 'length', 'max' => 20),
			array('name', 'length', 'max' => 255),
			array('created_at, updated_at, deleted_at', 'safe'),
			array('max_per_org, is_active, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id,event_name, name, start_time, end_time, max_per_org, is_active, note, created_at, updated_at, deleted_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'registrations' => array(self::HAS_MANY, 'Registrations', 'period_id'),
		);
	}

	public function pivotModels()
	{
		return array();
	}

	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'name' => Yii::t('app', 'Tên đợt đăng ký'),
			'start_time' => Yii::t('app', 'Ngày bắt đầu'),
			'end_time' => Yii::t('app', 'Ngày kết thúc'),
			'max_per_org' => Yii::t('app', 'Số lượng tối đa'),
			'is_active' => Yii::t('app', 'Kích hoạt'),
			'note' => Yii::t('app', 'Ghi chú'),
			'created_at' => Yii::t('app', 'Ngày tạo'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'event' => null,
			'registrations' => null,
		);
	}

	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('event_name', $this->event_name);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('end_time', $this->end_time, true);
		$criteria->compare('max_per_org', $this->max_per_org);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('note', $this->note);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
