<?php

/**
 * This is the model base class for the table "beauty_scores".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BeautyScores".
 *
 * Columns in table "beauty_scores" available as properties of the model,
 * followed by relations of table "beauty_scores" available as properties of the model.
 *
 * @property string $id
 * @property string $round_id
 * @property string $contestant_id
 * @property string $judge_id
 * @property string $score
 * @property string $note
 * @property string $scored_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property BeautyContestants $contestant
 * @property BeautyRounds $round
 */
abstract class BaseBeautyScores extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'beauty_scores';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BeautyScores|BeautyScores', $n);
	}

	public static function representingColumn() {
		return 'score';
	}

	public function rules() {
		return array(
			array('round_id, contestant_id, judge_id, score', 'required'),
			array('round_id, contestant_id, judge_id', 'length', 'max'=>20),
			array('score', 'length', 'max'=>8),
			array('note, scored_at, created_at, updated_at, deleted_at', 'safe'),
			array('note, scored_at, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, round_id, contestant_id, judge_id, score, note, scored_at, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'contestant' => array(self::BELONGS_TO, 'BeautyContestants', 'contestant_id'),
			'round' => array(self::BELONGS_TO, 'BeautyRounds', 'round_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'round_id' => null,
			'contestant_id' => null,
			'judge_id' => Yii::t('app', 'Judge'),
			'score' => Yii::t('app', 'Score'),
			'note' => Yii::t('app', 'Note'),
			'scored_at' => Yii::t('app', 'Scored At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'contestant' => null,
			'round' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('round_id', $this->round_id);
		$criteria->compare('contestant_id', $this->contestant_id);
		$criteria->compare('judge_id', $this->judge_id, true);
		$criteria->compare('score', $this->score, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('scored_at', $this->scored_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}