<?php

/**
 * This is the model base class for the table "beauty_contests".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BeautyContests".
 *
 * Columns in table "beauty_contests" available as properties of the model,
 * followed by relations of table "beauty_contests" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $name
 * @property string $description
 * @property string $gender
 * @property integer $age_min
 * @property integer $age_max
 * @property string $registration_open_at
 * @property string $registration_close_at
 * @property string $contest_date
 * @property string $location
 * @property string $candidate_prefix
 * @property integer $candidate_start
 * @property integer $max_per_org
 * @property integer $is_active
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property BeautyContestants[] $beautyContestants
 * @property Events $event
 * @property BeautyRounds[] $beautyRounds
 */
abstract class BaseBeautyContests extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'beauty_contests';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BeautyContests|BeautyContests', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('event_id, name, age_min, age_max, candidate_start', 'required'),
			array('age_min, age_max, candidate_start, max_per_org, is_active', 'numerical', 'integerOnly'=>true),
			array('event_id', 'length', 'max'=>20),
			array('name, location', 'length', 'max'=>255),
			array('gender', 'length', 'max'=>6),
			array('candidate_prefix', 'length', 'max'=>50),
			array('description, registration_open_at, registration_close_at, contest_date, created_at, updated_at, deleted_at', 'safe'),
			array('description, gender, registration_open_at, registration_close_at, contest_date, location, candidate_prefix, max_per_org, is_active, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, name, description, gender, age_min, age_max, registration_open_at, registration_close_at, contest_date, location, candidate_prefix, candidate_start, max_per_org, is_active, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'beautyContestants' => array(self::HAS_MANY, 'BeautyContestants', 'contest_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'beautyRounds' => array(self::HAS_MANY, 'BeautyRounds', 'contest_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'gender' => Yii::t('app', 'Gender'),
			'age_min' => Yii::t('app', 'Age Min'),
			'age_max' => Yii::t('app', 'Age Max'),
			'registration_open_at' => Yii::t('app', 'Registration Open At'),
			'registration_close_at' => Yii::t('app', 'Registration Close At'),
			'contest_date' => Yii::t('app', 'Contest Date'),
			'location' => Yii::t('app', 'Location'),
			'candidate_prefix' => Yii::t('app', 'Candidate Prefix'),
			'candidate_start' => Yii::t('app', 'Candidate Start'),
			'max_per_org' => Yii::t('app', 'Max Per Org'),
			'is_active' => Yii::t('app', 'Is Active'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'beautyContestants' => null,
			'event' => null,
			'beautyRounds' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('age_min', $this->age_min);
		$criteria->compare('age_max', $this->age_max);
		$criteria->compare('registration_open_at', $this->registration_open_at, true);
		$criteria->compare('registration_close_at', $this->registration_close_at, true);
		$criteria->compare('contest_date', $this->contest_date, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('candidate_prefix', $this->candidate_prefix, true);
		$criteria->compare('candidate_start', $this->candidate_start);
		$criteria->compare('max_per_org', $this->max_per_org);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}