<?php

/**
 * This is the model base class for the table "positions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Positions".
 *
 * Columns in table "positions" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $unique_code
 * @property string $property_code
 * @property string $division_code
 * @property string $department_code
 * @property integer $level
 * @property string $code
 * @property string $name
 * @property integer $amount
 * @property string $notes
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 */
abstract class BasePositions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'positions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Positions|Positions', $n);
	}

	public static function representingColumn() {
		return 'unique_code';
	}

	public function rules() {
		return array(
			array('unique_code, property_code, division_code, department_code, level, code, name', 'required'),
			array('level, amount, status', 'numerical', 'integerOnly'=>true),
			array('unique_code', 'length', 'max'=>100),
			array('property_code, division_code, department_code', 'length', 'max'=>50),
			array('code, name', 'length', 'max'=>255),
			array('notes, created_at, updated_at, deleted_at', 'safe'),
			array('amount, notes, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, unique_code, property_code, division_code, department_code, level, code, name, amount, notes, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'unique_code' => Yii::t('app', 'Unique Code'),
			'property_code' => Yii::t('app', 'Property Code'),
			'division_code' => Yii::t('app', 'Division Code'),
			'department_code' => Yii::t('app', 'Department Code'),
			'level' => Yii::t('app', 'Level'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'amount' => Yii::t('app', 'Amount'),
			'notes' => Yii::t('app', 'Notes'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('unique_code', $this->unique_code, true);
		$criteria->compare('property_code', $this->property_code, true);
		$criteria->compare('division_code', $this->division_code, true);
		$criteria->compare('department_code', $this->department_code, true);
		$criteria->compare('level', $this->level);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('amount', $this->amount);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}