<?php

/**
 * This is the model base class for the table "staffs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Staffs".
 *
 * Columns in table "staffs" available as properties of the model,
 * followed by relations of table "staffs" available as properties of the model.
 *
 * @property string $id
 * @property string $unique_code
 * @property string $department_code
 * @property string $id_card
 * @property string $rank_id
 * @property string $position_code
 * @property string $property_code
 * @property string $division_code
 * @property string $code
 * @property integer $is_lecturer
 * @property integer $curren_job_id
 * @property string $lecturer_type
 * @property string $first_name
 * @property string $last_name
 * @property string $full_name
 * @property string $email
 * @property string $phone
 * @property string $birthday
 * @property string $terminate_date
 * @property string $join_hotel_date
 * @property string $end_testing_date
 * @property integer $married
 * @property integer $gender
 * @property string $address
 * @property string $notes
 * @property integer $status
 * @property string $staff_type
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees[] $attendees
 */
abstract class BaseStaffs extends GxActiveRecord
{

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'staffs';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'Nhân viên', $n);
	}

	public static function representingColumn()
	{
		return 'unique_code';
	}

	public function rules()
	{
		return array(
			array('unique_code, department_code, id_card, rank_id, position_code, property_code, division_code, code, curren_job_id', 'required'),
			array('is_lecturer, curren_job_id, married, gender, status', 'numerical', 'integerOnly' => true),
			array('unique_code, first_name, last_name, email, phone', 'length', 'max' => 100),
			array('department_code, position_code, property_code, division_code, full_name, address, staff_type', 'length', 'max' => 255),
			array('id_card, rank_id, code', 'length', 'max' => 50),
			array('lecturer_type', 'length', 'max' => 20),
			array('birthday, terminate_date, join_hotel_date, end_testing_date, notes, created_at, updated_at, deleted_at', 'safe'),
			array('is_lecturer, lecturer_type, first_name, last_name, full_name, email, phone, birthday, terminate_date, join_hotel_date, end_testing_date, married, gender, address, notes, status, staff_type, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, unique_code, department_code, id_card, rank_id, position_code, property_code, division_code, code, is_lecturer, curren_job_id, lecturer_type, first_name, last_name, full_name, email, phone, birthday, terminate_date, join_hotel_date, end_testing_date, married, gender, address, notes, status, staff_type, created_at, updated_at, deleted_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
			'attendees' => array(self::HAS_MANY, 'Attendees', 'staff_id'),
		);
	}

	public function pivotModels()
	{
		return array();
	}

	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('app', 'ID'),
			'unique_code' => Yii::t('app', 'Unique Code'),
			'department_code' => Yii::t('app', 'Department Code'),
			'id_card' => Yii::t('app', 'Id Card'),
			'rank_id' => Yii::t('app', 'Rank'),
			'position_code' => Yii::t('app', 'Position Code'),
			'property_code' => Yii::t('app', 'Property Code'),
			'division_code' => Yii::t('app', 'Division Code'),
			'code' => Yii::t('app', 'Code'),
			'is_lecturer' => Yii::t('app', 'Is Lecturer'),
			'curren_job_id' => Yii::t('app', 'Curren Job'),
			'lecturer_type' => Yii::t('app', 'Lecturer Type'),
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'full_name' => Yii::t('app', 'Full Name'),
			'email' => Yii::t('app', 'Email'),
			'phone' => Yii::t('app', 'Phone'),
			'birthday' => Yii::t('app', 'Birthday'),
			'terminate_date' => Yii::t('app', 'Terminate Date'),
			'join_hotel_date' => Yii::t('app', 'Join Hotel Date'),
			'end_testing_date' => Yii::t('app', 'End Testing Date'),
			'married' => Yii::t('app', 'Married'),
			'gender' => Yii::t('app', 'Gender'),
			'address' => Yii::t('app', 'Address'),
			'notes' => Yii::t('app', 'Notes'),
			'status' => Yii::t('app', 'Status'),
			'staff_type' => Yii::t('app', 'Staff Type'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendees' => null,
		);
	}

	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('unique_code', $this->unique_code, true);
		$criteria->compare('department_code', $this->department_code, true);
		$criteria->compare('id_card', $this->id_card, true);
		$criteria->compare('rank_id', $this->rank_id, true);
		$criteria->compare('position_code', $this->position_code, true);
		$criteria->compare('property_code', $this->property_code, true);
		$criteria->compare('division_code', $this->division_code, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('is_lecturer', $this->is_lecturer);
		$criteria->compare('curren_job_id', $this->curren_job_id);
		$criteria->compare('lecturer_type', $this->lecturer_type, true);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('full_name', $this->full_name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('birthday', $this->birthday, true);
		$criteria->compare('terminate_date', $this->terminate_date, true);
		$criteria->compare('join_hotel_date', $this->join_hotel_date, true);
		$criteria->compare('end_testing_date', $this->end_testing_date, true);
		$criteria->compare('married', $this->married);
		$criteria->compare('gender', $this->gender);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('staff_type', $this->staff_type, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
