<?php

/**
 * This is the model base class for the table "talent_entry_members".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TalentEntryMembers".
 *
 * Columns in table "talent_entry_members" available as properties of the model,
 * followed by relations of table "talent_entry_members" available as properties of the model.
 *
 * @property string $id
 * @property string $entry_id
 * @property string $attendee_id
 * @property string $role
 * @property integer $is_lead
 * @property integer $sort_order
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property TalentEntries $entry
 */
abstract class BaseTalentEntryMembers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'talent_entry_members';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TalentEntryMembers|TalentEntryMembers', $n);
	}

	public static function representingColumn() {
		return 'role';
	}

	public function rules() {
		return array(
			array('entry_id, attendee_id', 'required'),
			array('is_lead, sort_order', 'numerical', 'integerOnly'=>true),
			array('entry_id, attendee_id', 'length', 'max'=>20),
			array('role', 'length', 'max'=>100),
			array('created_at, updated_at, deleted_at', 'safe'),
			array('role, is_lead, sort_order, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, entry_id, attendee_id, role, is_lead, sort_order, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'entry' => array(self::BELONGS_TO, 'TalentEntries', 'entry_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'entry_id' => null,
			'attendee_id' => null,
			'role' => Yii::t('app', 'Role'),
			'is_lead' => Yii::t('app', 'Is Lead'),
			'sort_order' => Yii::t('app', 'Sort Order'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'entry' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('entry_id', $this->entry_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('role', $this->role, true);
		$criteria->compare('is_lead', $this->is_lead);
		$criteria->compare('sort_order', $this->sort_order);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}