<?php

/**
 * This is the model base class for the table "logs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Logs".
 *
 * Columns in table "logs" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $module
 * @property string $user_id
 * @property string $model_id
 * @property string $action
 * @property string $old_data
 * @property string $new_data
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 */
abstract class BaseLogs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'logs';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Logs|Logs', $n);
	}

	public static function representingColumn() {
		return 'module';
	}

	public function rules() {
		return array(
			array('module, user_id, action', 'required'),
			array('module', 'length', 'max'=>255),
			array('user_id, model_id', 'length', 'max'=>20),
			array('action', 'length', 'max'=>100),
			array('old_data, new_data, created_at, updated_at, deleted_at', 'safe'),
			array('model_id, old_data, new_data, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, module, user_id, model_id, action, old_data, new_data, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'module' => Yii::t('app', 'Module'),
			'user_id' => Yii::t('app', 'User'),
			'model_id' => Yii::t('app', 'Model'),
			'action' => Yii::t('app', 'Action'),
			'old_data' => Yii::t('app', 'Old Data'),
			'new_data' => Yii::t('app', 'New Data'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('module', $this->module, true);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('model_id', $this->model_id, true);
		$criteria->compare('action', $this->action, true);
		$criteria->compare('old_data', $this->old_data, true);
		$criteria->compare('new_data', $this->new_data, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}