<?php

/**
 * This is the model base class for the table "meal_attendees".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MealAttendees".
 *
 * Columns in table "meal_attendees" available as properties of the model,
 * followed by relations of table "meal_attendees" available as properties of the model.
 *
 * @property string $id
 * @property string $meal_id
 * @property string $attendee_id
 * @property string $table_id
 * @property string $status
 * @property string $description
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property Meals $meal
 * @property MealTables $table
 */
abstract class BaseMealAttendees extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'meal_attendees';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MealAttendees|MealAttendees', $n);
	}

	public static function representingColumn() {
		return 'status';
	}

	public function rules() {
		return array(
			array('meal_id, attendee_id, table_id', 'required'),
			array('meal_id, attendee_id, table_id', 'length', 'max'=>20),
			array('status', 'length', 'max'=>10),
			array('description, created_at, updated_at, deleted_at', 'safe'),
			array('status, description, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, meal_id, attendee_id, table_id, status, description, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'meal' => array(self::BELONGS_TO, 'Meals', 'meal_id'),
			'table' => array(self::BELONGS_TO, 'MealTables', 'table_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'meal_id' => null,
			'attendee_id' => null,
			'table_id' => null,
			'status' => Yii::t('app', 'Status'),
			'description' => Yii::t('app', 'Description'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'meal' => null,
			'table' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('meal_id', $this->meal_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('table_id', $this->table_id);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}