<?php

/**
 * This is the model base class for the table "registration_details".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RegistrationDetails".
 *
 * Columns in table "registration_details" available as properties of the model,
 * followed by relations of table "registration_details" available as properties of the model.
 *
 * @property string $id
 * @property string $registration_id
 * @property string $role_id
 * @property string $content_id
 * @property string $sport_id
 * @property string $competition_id
 * @property integer $quantity
 * @property string $note
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Competitions $competition
 * @property Contents $content
 * @property Registrations $registration
 * @property Roles $role
 * @property Sports $sport
 */
abstract class BaseRegistrationDetails extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'registration_details';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RegistrationDetails|RegistrationDetails', $n);
	}

	public static function representingColumn() {
		return 'note';
	}

	public function rules() {
		return array(
			array('registration_id', 'required'),
			array('quantity, status', 'numerical', 'integerOnly'=>true),
			array('registration_id, role_id, content_id, sport_id, competition_id', 'length', 'max'=>20),
			array('note, created_at, updated_at, deleted_at', 'safe'),
			array('role_id, content_id, sport_id, competition_id, quantity, note, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, registration_id, role_id, content_id, sport_id, competition_id, quantity, note, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'competition' => array(self::BELONGS_TO, 'Competitions', 'competition_id'),
			'content' => array(self::BELONGS_TO, 'Contents', 'content_id'),
			'registration' => array(self::BELONGS_TO, 'Registrations', 'registration_id'),
			'role' => array(self::BELONGS_TO, 'Roles', 'role_id'),
			'sport' => array(self::BELONGS_TO, 'Sports', 'sport_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'registration_id' => null,
			'role_id' => null,
			'content_id' => null,
			'sport_id' => null,
			'competition_id' => null,
			'quantity' => Yii::t('app', 'Quantity'),
			'note' => Yii::t('app', 'Note'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'competition' => null,
			'content' => null,
			'registration' => null,
			'role' => null,
			'sport' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('registration_id', $this->registration_id);
		$criteria->compare('role_id', $this->role_id);
		$criteria->compare('content_id', $this->content_id);
		$criteria->compare('sport_id', $this->sport_id);
		$criteria->compare('competition_id', $this->competition_id);
		$criteria->compare('quantity', $this->quantity);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}