<?php

/**
 * This is the model base class for the table "roles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Roles".
 *
 * Columns in table "roles" available as properties of the model,
 * followed by relations of table "roles" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $name
 * @property string $code
 * @property string $color
 * @property string $icon
 * @property integer $sort_order
 * @property string $description
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property AttendeeRoles[] $attendeeRoles
 * @property Attendees[] $attendees
 * @property RegistrationDetails[] $registrationDetails
 * @property Events $event
 */
abstract class BaseRoles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'roles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Roles|Roles', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('sort_order', 'numerical', 'integerOnly'=>true),
			array('event_id', 'length', 'max'=>20),
			array('name', 'length', 'max'=>100),
			array('code, color, icon', 'length', 'max'=>50),
			array('description, created_at, updated_at, deleted_at', 'safe'),
			array('event_id, code, color, icon, sort_order, description, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, name, code, color, icon, sort_order, description, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendeeRoles' => array(self::HAS_MANY, 'AttendeeRoles', 'role_id'),
			'attendees' => array(self::HAS_MANY, 'Attendees', 'role_id'),
			'registrationDetails' => array(self::HAS_MANY, 'RegistrationDetails', 'role_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'name' => Yii::t('app', 'Name'),
			'code' => Yii::t('app', 'Code'),
			'color' => Yii::t('app', 'Color'),
			'icon' => Yii::t('app', 'Icon'),
			'sort_order' => Yii::t('app', 'Sort Order'),
			'description' => Yii::t('app', 'Description'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendeeRoles' => null,
			'attendees' => null,
			'registrationDetails' => null,
			'event' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('color', $this->color, true);
		$criteria->compare('icon', $this->icon, true);
		$criteria->compare('sort_order', $this->sort_order);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}