<?php

/**
 * This is the model base class for the table "User".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "User" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Id
 * @property integer $EmployeeId
 * @property string $Email
 * @property string $Password
 * @property string $DisplayName
 * @property string $CreatedAt
 * @property string $UpdatedAt
 * @property boolean $IsDelete
 * @property boolean $IsActive
 *
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'User';
	}

	public static function representingColumn() {
		return 'Email';
	}

	public function rules() {
		return array(
			array('EmployeeId', 'numerical', 'integerOnly'=>true),
			array('Email', 'length', 'max'=>50),
			array('Password, DisplayName', 'length', 'max'=>100),
			array('CreatedAt, UpdatedAt, IsDelete, IsActive', 'safe'),
			array('EmployeeId, Email, Password, DisplayName, CreatedAt, UpdatedAt, IsDelete, IsActive', 'default', 'setOnEmpty' => true, 'value' => null),
			array('Id, EmployeeId, Email, Password, DisplayName, CreatedAt, UpdatedAt, IsDelete, IsActive', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'Id' => Yii::t('app', 'ID'),
			'EmployeeId' => Yii::t('app', 'Employee'),
			'Email' => Yii::t('app', 'Email'),
			'Password' => Yii::t('app', 'Password'),
			'DisplayName' => Yii::t('app', 'Display Name'),
			'CreatedAt' => Yii::t('app', 'Created At'),
			'UpdatedAt' => Yii::t('app', 'Updated At'),
			'IsDelete' => Yii::t('app', 'Is Delete'),
			'IsActive' => Yii::t('app', 'Is Active'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Id', $this->Id);
		$criteria->compare('EmployeeId', $this->EmployeeId);
		$criteria->compare('Email', $this->Email, true);
		$criteria->compare('Password', $this->Password, true);
		$criteria->compare('DisplayName', $this->DisplayName, true);
		$criteria->compare('CreatedAt', $this->CreatedAt, true);
		$criteria->compare('UpdatedAt', $this->UpdatedAt, true);
		$criteria->compare('IsDelete', $this->IsDelete);
		$criteria->compare('IsActive', $this->IsActive);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}