<?php

/**
 * This is the model base class for the table "badges".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Badges".
 *
 * Columns in table "badges" available as properties of the model,
 * followed by relations of table "badges" available as properties of the model.
 *
 * @property string $id
 * @property string $attendee_id
 * @property string $template_id
 * @property string $generated_path
 * @property string $width_mm
 * @property string $height_mm
 * @property integer $dpi
 * @property string $generated_at
 * @property integer $print_count
 * @property string $last_printed_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 */
abstract class BaseBadges extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'badges';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Badges|Badges', $n);
	}

	public static function representingColumn() {
		return 'width_mm';
	}

	public function rules() {
		return array(
			array('attendee_id', 'required'),
			array('dpi, print_count', 'numerical', 'integerOnly'=>true),
			array('attendee_id, template_id', 'length', 'max'=>20),
			array('generated_path', 'length', 'max'=>500),
			array('width_mm, height_mm', 'length', 'max'=>6),
			array('generated_at, last_printed_at, created_at, updated_at, deleted_at', 'safe'),
			array('template_id, generated_path, width_mm, height_mm, dpi, generated_at, print_count, last_printed_at, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, attendee_id, template_id, generated_path, width_mm, height_mm, dpi, generated_at, print_count, last_printed_at, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'attendee_id' => null,
			'template_id' => Yii::t('app', 'Template'),
			'generated_path' => Yii::t('app', 'Generated Path'),
			'width_mm' => Yii::t('app', 'Width Mm'),
			'height_mm' => Yii::t('app', 'Height Mm'),
			'dpi' => Yii::t('app', 'Dpi'),
			'generated_at' => Yii::t('app', 'Generated At'),
			'print_count' => Yii::t('app', 'Print Count'),
			'last_printed_at' => Yii::t('app', 'Last Printed At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('template_id', $this->template_id, true);
		$criteria->compare('generated_path', $this->generated_path, true);
		$criteria->compare('width_mm', $this->width_mm, true);
		$criteria->compare('height_mm', $this->height_mm, true);
		$criteria->compare('dpi', $this->dpi);
		$criteria->compare('generated_at', $this->generated_at, true);
		$criteria->compare('print_count', $this->print_count);
		$criteria->compare('last_printed_at', $this->last_printed_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}