<?php

/**
 * This is the model base class for the table "banquet_tables".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BanquetTables".
 *
 * Columns in table "banquet_tables" available as properties of the model,
 * followed by relations of table "banquet_tables" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property integer $table_number
 * @property string $label
 * @property integer $capacity
 * @property integer $pos_x
 * @property integer $pos_y
 * @property string $shape
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property BanquetSeats[] $banquetSeats
 * @property BanquetEvents $event
 */
abstract class BaseBanquetTables extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banquet_tables';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BanquetTables|BanquetTables', $n);
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('event_id, table_number, label', 'required'),
			array('table_number, capacity, pos_x, pos_y', 'numerical', 'integerOnly'=>true),
			array('event_id', 'length', 'max'=>20),
			array('label', 'length', 'max'=>100),
			array('shape', 'length', 'max'=>9),
			array('note, created_at, updated_at, deleted_at', 'safe'),
			array('capacity, pos_x, pos_y, shape, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, table_number, label, capacity, pos_x, pos_y, shape, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'banquetSeats' => array(self::HAS_MANY, 'BanquetSeats', 'table_id'),
			'event' => array(self::BELONGS_TO, 'BanquetEvents', 'event_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'table_number' => Yii::t('app', 'Table Number'),
			'label' => Yii::t('app', 'Label'),
			'capacity' => Yii::t('app', 'Capacity'),
			'pos_x' => Yii::t('app', 'Pos X'),
			'pos_y' => Yii::t('app', 'Pos Y'),
			'shape' => Yii::t('app', 'Shape'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'banquetSeats' => null,
			'event' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('table_number', $this->table_number);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('capacity', $this->capacity);
		$criteria->compare('pos_x', $this->pos_x);
		$criteria->compare('pos_y', $this->pos_y);
		$criteria->compare('shape', $this->shape, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}