<?php

/**
 * This is the model base class for the table "meal_checkins".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MealCheckins".
 *
 * Columns in table "meal_checkins" available as properties of the model,
 * followed by relations of table "meal_checkins" available as properties of the model.
 *
 * @property string $id
 * @property string $meal_id
 * @property string $attendee_id
 * @property string $check_in_time
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property Meals $meal
 */
abstract class BaseMealCheckins extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'meal_checkins';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MealCheckins|MealCheckins', $n);
	}

	public static function representingColumn() {
		return 'check_in_time';
	}

	public function rules() {
		return array(
			array('meal_id, attendee_id, check_in_time, status', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('meal_id, attendee_id', 'length', 'max'=>20),
			array('created_at, updated_at, deleted_at', 'safe'),
			array('created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, meal_id, attendee_id, check_in_time, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'meal' => array(self::BELONGS_TO, 'Meals', 'meal_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'meal_id' => null,
			'attendee_id' => null,
			'check_in_time' => Yii::t('app', 'Check In Time'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'meal' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('meal_id', $this->meal_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('check_in_time', $this->check_in_time, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}