<?php

/**
 * This is the model base class for the table "event_units".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventUnits".
 *
 * Columns in table "event_units" available as properties of the model,
 * followed by relations of table "event_units" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $property_id
 * @property string $status
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Events $event
 * @property Properties $property
 */
abstract class BaseEventUnits extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'event_units';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EventUnits|EventUnits', $n);
	}

	public static function representingColumn() {
		return 'status';
	}

	public function rules() {
		return array(
			array('event_id, property_id', 'required'),
			array('event_id, property_id', 'length', 'max'=>20),
			array('status', 'length', 'max'=>9),
			array('note, created_at, updated_at, deleted_at', 'safe'),
			array('status, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, property_id, status, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'property' => array(self::BELONGS_TO, 'Properties', 'property_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'property_id' => null,
			'status' => Yii::t('app', 'Status'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'event' => null,
			'property' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('property_id', $this->property_id);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}