<?php

/**
 * This is the model base class for the table "sport_teams".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportTeams".
 *
 * Columns in table "sport_teams" available as properties of the model,
 * followed by relations of table "sport_teams" available as properties of the model.
 *
 * @property string $id
 * @property string $code
 * @property string $name
 * @property string $event_id
 * @property string $sport_id
 * @property string $property_id
 * @property string $short_name
 * @property string $color
 * @property integer $is_active
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property SportMatchResults[] $sportMatchResults
 * @property SportMatches[] $sportMatches
 * @property SportMatches[] $sportMatches1
 * @property SportStageTeams[] $sportStageTeams
 * @property SportStandings[] $sportStandings
 * @property SportTeamMembers[] $sportTeamMembers
 * @property Events $event
 * @property Properties $property
 * @property Sports $sport
 */
abstract class BaseSportTeams extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_teams';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportTeams|SportTeams', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, name, sport_id', 'required'),
			array('is_active', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>50),
			array('name', 'length', 'max'=>255),
			array('event_id, sport_id, property_id, color', 'length', 'max'=>20),
			array('short_name', 'length', 'max'=>100),
			array('created_at, updated_at, deleted_at', 'safe'),
			array('event_id, property_id, short_name, color, is_active, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, event_id, sport_id, property_id, short_name, color, is_active, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sportMatchResults' => array(self::HAS_MANY, 'SportMatchResults', 'winner_team_id'),
			'sportMatches' => array(self::HAS_MANY, 'SportMatches', 'team_a_id'),
			'sportMatches1' => array(self::HAS_MANY, 'SportMatches', 'team_b_id'),
			'sportStageTeams' => array(self::HAS_MANY, 'SportStageTeams', 'team_id'),
			'sportStandings' => array(self::HAS_MANY, 'SportStandings', 'team_id'),
			'sportTeamMembers' => array(self::HAS_MANY, 'SportTeamMembers', 'sport_team_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'property' => array(self::BELONGS_TO, 'Properties', 'property_id'),
			'sport' => array(self::BELONGS_TO, 'Sports', 'sport_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'event_id' => null,
			'sport_id' => null,
			'property_id' => null,
			'short_name' => Yii::t('app', 'Short Name'),
			'color' => Yii::t('app', 'Color'),
			'is_active' => Yii::t('app', 'Is Active'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'sportMatchResults' => null,
			'sportMatches' => null,
			'sportMatches1' => null,
			'sportStageTeams' => null,
			'sportStandings' => null,
			'sportTeamMembers' => null,
			'event' => null,
			'property' => null,
			'sport' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('sport_id', $this->sport_id);
		$criteria->compare('property_id', $this->property_id);
		$criteria->compare('short_name', $this->short_name, true);
		$criteria->compare('color', $this->color, true);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}