<?php

/**
 * This is the model base class for the table "departments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Departments".
 *
 * Columns in table "departments" available as properties of the model,
 * followed by relations of table "departments" available as properties of the model.
 *
 * @property string $id
 * @property string $property_code
 * @property string $division_code
 * @property string $unique_code
 * @property string $code
 * @property string $name
 * @property integer $total_member
 * @property string $notes
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property UnitAccounts[] $unitAccounts
 */
abstract class BaseDepartments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'departments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Departments|Departments', $n);
	}

	public static function representingColumn() {
		return 'property_code';
	}

	public function rules() {
		return array(
			array('property_code, division_code, unique_code, code, name', 'required'),
			array('total_member, status', 'numerical', 'integerOnly'=>true),
			array('property_code, division_code, code', 'length', 'max'=>50),
			array('unique_code', 'length', 'max'=>100),
			array('name', 'length', 'max'=>255),
			array('notes, created_at, updated_at, deleted_at', 'safe'),
			array('total_member, notes, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, property_code, division_code, unique_code, code, name, total_member, notes, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'unitAccounts' => array(self::HAS_MANY, 'UnitAccounts', 'department_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'property_code' => Yii::t('app', 'Property Code'),
			'division_code' => Yii::t('app', 'Division Code'),
			'unique_code' => Yii::t('app', 'Unique Code'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'total_member' => Yii::t('app', 'Total Member'),
			'notes' => Yii::t('app', 'Notes'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'unitAccounts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('property_code', $this->property_code, true);
		$criteria->compare('division_code', $this->division_code, true);
		$criteria->compare('unique_code', $this->unique_code, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('total_member', $this->total_member);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}