<?php

/**
 * This is the model base class for the table "banquet_seats".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BanquetSeats".
 *
 * Columns in table "banquet_seats" available as properties of the model,
 * followed by relations of table "banquet_seats" available as properties of the model.
 *
 * @property string $id
 * @property string $table_id
 * @property string $attendee_id
 * @property string $assigned_by
 * @property string $assigned_at
 * @property integer $seat_number
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property BanquetTables $table
 */
abstract class BaseBanquetSeats extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banquet_seats';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BanquetSeats|BanquetSeats', $n);
	}

	public static function representingColumn() {
		return 'assigned_at';
	}

	public function rules() {
		return array(
			array('table_id', 'required'),
			array('seat_number', 'numerical', 'integerOnly'=>true),
			array('table_id, attendee_id, assigned_by', 'length', 'max'=>20),
			array('assigned_at, created_at, updated_at, deleted_at', 'safe'),
			array('attendee_id, assigned_by, assigned_at, seat_number, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, table_id, attendee_id, assigned_by, assigned_at, seat_number, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'table' => array(self::BELONGS_TO, 'BanquetTables', 'table_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'table_id' => null,
			'attendee_id' => null,
			'assigned_by' => Yii::t('app', 'Assigned By'),
			'assigned_at' => Yii::t('app', 'Assigned At'),
			'seat_number' => Yii::t('app', 'Seat Number'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'table' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('table_id', $this->table_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('assigned_by', $this->assigned_by, true);
		$criteria->compare('assigned_at', $this->assigned_at, true);
		$criteria->compare('seat_number', $this->seat_number);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}