<?php

/**
 * This is the model base class for the table "m_controllers".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MControllers".
 *
 * Columns in table "m_controllers" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $code
 * @property integer $parent_id
 * @property string $title
 * @property integer $sort
 * @property integer $menu
 * @property integer $permission
 *
 */
abstract class BaseMControllers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'm_controllers';
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('code, parent_id, title', 'required'),
			array('parent_id, sort, menu, permission', 'numerical', 'integerOnly'=>true),
			array('code, title', 'length', 'max'=>255),
			array('sort, menu, permission', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, parent_id, title, sort, menu, permission', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'parent_id' => Yii::t('app', 'Parent'),
			'title' => Yii::t('app', 'Title'),
			'sort' => Yii::t('app', 'Sort'),
			'menu' => Yii::t('app', 'Menu'),
			'permission' => Yii::t('app', 'Permission'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('sort', $this->sort);
		$criteria->compare('menu', $this->menu);
		$criteria->compare('permission', $this->permission);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 50,
            ),
		));
	}
}