<?php

/**
 * This is the model base class for the table "attendee_roles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AttendeeRoles".
 *
 * Columns in table "attendee_roles" available as properties of the model,
 * followed by relations of table "attendee_roles" available as properties of the model.
 *
 * @property string $id
 * @property string $attendee_id
 * @property string $role_id
 * @property string $assigned_by
 * @property string $assigned_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property Roles $role
 */
abstract class BaseAttendeeRoles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'attendee_roles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AttendeeRoles|AttendeeRoles', $n);
	}

	public static function representingColumn() {
		return 'assigned_at';
	}

	public function rules() {
		return array(
			array('attendee_id, role_id', 'required'),
			array('attendee_id, role_id, assigned_by', 'length', 'max'=>20),
			array('assigned_at, created_at, updated_at, deleted_at', 'safe'),
			array('assigned_by, assigned_at, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, attendee_id, role_id, assigned_by, assigned_at, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'role' => array(self::BELONGS_TO, 'Roles', 'role_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'attendee_id' => null,
			'role_id' => null,
			'assigned_by' => Yii::t('app', 'Assigned By'),
			'assigned_at' => Yii::t('app', 'Assigned At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'role' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('role_id', $this->role_id);
		$criteria->compare('assigned_by', $this->assigned_by, true);
		$criteria->compare('assigned_at', $this->assigned_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}