<?php

/**
 * This is the model base class for the table "meals".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Meals".
 *
 * Columns in table "meals" available as properties of the model,
 * followed by relations of table "meals" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $name
 * @property string $meal_date
 * @property string $meal_type
 * @property string $serving_time
 * @property string $cutoff_deadline
 * @property string $location
 * @property integer $total_count
 * @property string $description
 * @property integer $is_active
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property MealAttendees[] $mealAttendees
 * @property MealCheckins[] $mealCheckins
 * @property MealCutoffs[] $mealCutoffs
 * @property MealTables[] $mealTables
 * @property MealVouchers[] $mealVouchers
 * @property Events $event
 */
abstract class BaseMeals extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'meals';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Meals|Meals', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('event_id, name, meal_date, meal_type, serving_time, cutoff_deadline', 'required'),
			array('total_count, is_active', 'numerical', 'integerOnly'=>true),
			array('event_id', 'length', 'max'=>20),
			array('name, location', 'length', 'max'=>255),
			array('meal_type', 'length', 'max'=>9),
			array('description, created_at, updated_at, deleted_at', 'safe'),
			array('location, total_count, description, is_active, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, name, meal_date, meal_type, serving_time, cutoff_deadline, location, total_count, description, is_active, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mealAttendees' => array(self::HAS_MANY, 'MealAttendees', 'meal_id'),
			'mealCheckins' => array(self::HAS_MANY, 'MealCheckins', 'meal_id'),
			'mealCutoffs' => array(self::HAS_MANY, 'MealCutoffs', 'meal_id'),
			'mealTables' => array(self::HAS_MANY, 'MealTables', 'meal_id'),
			'mealVouchers' => array(self::HAS_MANY, 'MealVouchers', 'meal_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'name' => Yii::t('app', 'Name'),
			'meal_date' => Yii::t('app', 'Meal Date'),
			'meal_type' => Yii::t('app', 'Meal Type'),
			'serving_time' => Yii::t('app', 'Serving Time'),
			'cutoff_deadline' => Yii::t('app', 'Cutoff Deadline'),
			'location' => Yii::t('app', 'Location'),
			'total_count' => Yii::t('app', 'Total Count'),
			'description' => Yii::t('app', 'Description'),
			'is_active' => Yii::t('app', 'Is Active'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'mealAttendees' => null,
			'mealCheckins' => null,
			'mealCutoffs' => null,
			'mealTables' => null,
			'mealVouchers' => null,
			'event' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('meal_date', $this->meal_date, true);
		$criteria->compare('meal_type', $this->meal_type, true);
		$criteria->compare('serving_time', $this->serving_time, true);
		$criteria->compare('cutoff_deadline', $this->cutoff_deadline, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('total_count', $this->total_count);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}