<?php

/**
 * This is the model base class for the table "talent_categories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TalentCategories".
 *
 * Columns in table "talent_categories" available as properties of the model,
 * followed by relations of table "talent_categories" available as properties of the model.
 *
 * @property string $id
 * @property string $code
 * @property string $name
 * @property string $type
 * @property integer $min_members
 * @property integer $max_members
 * @property integer $max_duration_seconds
 * @property string $description
 * @property integer $sort_order
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property TalentEntries[] $talentEntries
 */
abstract class BaseTalentCategories extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'talent_categories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TalentCategories|TalentCategories', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, name, min_members, max_members', 'required'),
			array('min_members, max_members, max_duration_seconds, sort_order', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>50),
			array('name', 'length', 'max'=>100),
			array('type', 'length', 'max'=>5),
			array('description, created_at, updated_at, deleted_at', 'safe'),
			array('type, max_duration_seconds, description, sort_order, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, type, min_members, max_members, max_duration_seconds, description, sort_order, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'talentEntries' => array(self::HAS_MANY, 'TalentEntries', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'type' => Yii::t('app', 'Type'),
			'min_members' => Yii::t('app', 'Min Members'),
			'max_members' => Yii::t('app', 'Max Members'),
			'max_duration_seconds' => Yii::t('app', 'Max Duration Seconds'),
			'description' => Yii::t('app', 'Description'),
			'sort_order' => Yii::t('app', 'Sort Order'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'talentEntries' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('min_members', $this->min_members);
		$criteria->compare('max_members', $this->max_members);
		$criteria->compare('max_duration_seconds', $this->max_duration_seconds);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('sort_order', $this->sort_order);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}