<?php

/**
 * This is the model base class for the table "talent_scores".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TalentScores".
 *
 * Columns in table "talent_scores" available as properties of the model,
 * followed by relations of table "talent_scores" available as properties of the model.
 *
 * @property string $id
 * @property string $entry_id
 * @property string $judge_id
 * @property double $score
 * @property string $criteria
 * @property string $note
 * @property string $scored_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property TalentEntries $entry
 */
abstract class BaseTalentScores extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'talent_scores';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TalentScores|TalentScores', $n);
	}

	public static function representingColumn() {
		return 'note';
	}

	public function rules() {
		return array(
			array('entry_id, judge_id, score, note', 'required'),
			array('score', 'numerical'),
			array('entry_id, judge_id', 'length', 'max'=>20),
			array('criteria', 'length', 'max'=>100),
			array('scored_at, created_at, updated_at, deleted_at', 'safe'),
			array('criteria, scored_at, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, entry_id, judge_id, score, criteria, note, scored_at, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'entry' => array(self::BELONGS_TO, 'TalentEntries', 'entry_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'entry_id' => null,
			'judge_id' => Yii::t('app', 'Judge'),
			'score' => Yii::t('app', 'Score'),
			'criteria' => Yii::t('app', 'Criteria'),
			'note' => Yii::t('app', 'Note'),
			'scored_at' => Yii::t('app', 'Scored At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'entry' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('entry_id', $this->entry_id);
		$criteria->compare('judge_id', $this->judge_id, true);
		$criteria->compare('score', $this->score);
		$criteria->compare('criteria', $this->criteria, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('scored_at', $this->scored_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}