<?php

/**
 * This is the model base class for the table "divisions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Divisions".
 *
 * Columns in table "divisions" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $property_code
 * @property string $unique_code
 * @property string $code
 * @property string $name
 * @property integer $total_staff
 * @property string $notes
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 */
abstract class BaseDivisions extends GxActiveRecord
{

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'divisions';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'Divisions|Divisions', $n);
	}

	public static function representingColumn()
	{
		return 'property_code';
	}

	public function rules()
	{
		return array(
			array('property_code, unique_code, code, name', 'required'),
			array('total_staff, status', 'numerical', 'integerOnly' => true),
			array('property_code, code', 'length', 'max' => 50),
			array('unique_code', 'length', 'max' => 100),
			array('name', 'length', 'max' => 255),
			array('notes, created_at, updated_at, deleted_at, property_name', 'safe'),
			array('total_staff, notes, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, property_code, unique_code, code, name, total_staff, notes, status, created_at, updated_at, deleted_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array();
	}

	public function pivotModels()
	{
		return array();
	}

	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('app', 'ID'),
			'property_code' => Yii::t('app', 'Property Code'),
			'unique_code' => Yii::t('app', 'Unique Code'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'total_staff' => Yii::t('app', 'Total Staff'),
			'notes' => Yii::t('app', 'Notes'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'property_name' => Yii::t('app', 'Tên đơn vị'),
		);
	}

	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('property_code', $this->property_code, true);
		$criteria->compare('unique_code', $this->unique_code, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('total_staff', $this->total_staff);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
