<?php

/**
 * This is the model base class for the table "m_users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MUsers".
 *
 * Columns in table "m_users" available as properties of the model,
 * followed by relations of table "m_users" available as properties of the model.
 *
 * @property integer $id
 * @property integer $role_id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $name
 * @property integer $gender
 * @property integer $status
 * @property string $created
 *
 * @property MRoles $role
 */
abstract class BaseMUsers extends GxActiveRecord
{

  public static function model($className = __CLASS__)
  {
    return parent::model($className);
  }

  public function tableName()
  {
    return 'm_users';
  }

  public static function representingColumn()
  {
    return 'username';
  }

  public function rules()
  {
    return array(
      array('role_id, password, email, name, gender, created', 'required'),
      array('role_id, gender, status', 'numerical', 'integerOnly' => true),
      array('username, password, email, name', 'length', 'max' => 255),
      array('status', 'default', 'setOnEmpty' => true, 'value' => null),
      array('coin, coin_block', 'safe'),
      array('id, role_id, username, password, email, name, gender, status, created,,image,info_file,date_upload_file,manageDepartment,can_create_report', 'safe', 'on' => 'search'),
    );
  }

  public function relations()
  {
    return array(
      'role' => array(self::BELONGS_TO, 'MRoles', 'role_id'),
      'hotel' => array(self::BELONGS_TO, 'MHotel', 'hotel_id'),
      'department' => array(self::BELONGS_TO, 'MDepartment', 'department_id'),
    );
  }

  public function pivotModels()
  {
    return array();
  }

  public function attributeLabels()
  {
    return array(
      'id' => Yii::t('app', 'ID'),
      'role_id' => null,
      'username' => Yii::t('app', 'Username'),
      'password' => Yii::t('app', 'Password'),
      'email' => Yii::t('app', 'Email'),
      'name' => Yii::t('app', 'Name'),
      'gender' => Yii::t('app', 'Gender'),
      'status' => Yii::t('app', 'Status'),
      'created' => Yii::t('app', 'Created'),
      'nhatuyendung_id' => Yii::t('app', 'Nhà tuyển dụng'),
      'can_create_report' => Yii::t('app', 'Có thể tạo báo cáo'),
      'role' => null,
    );
  }

  public function search()
  {
    $criteria = new CDbCriteria;
    $criteria->compare('id', $this->id);
    $criteria->compare('role_id', $this->role_id);
    $criteria->compare('username', $this->username, true);
    $criteria->compare('password', $this->password, true);
    $criteria->compare('email', $this->email, true);
    $criteria->compare('name', $this->name, true);
    $criteria->compare('gender', $this->gender);
    $criteria->compare('status', $this->status);
    $criteria->compare('created', $this->created, true);
    return new CActiveDataProvider($this, array(
      'criteria' => $criteria,
      'pagination' => array(
        'pageSize' => 50,
      ),
    ));
  }
}