<?php

/**
 * This is the model base class for the table "news".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "News".
 *
 * Columns in table "news" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $title
 * @property string $slug
 * @property string $excerpt
 * @property string $content
 * @property string $thumbnail
 * @property string $category_id
 * @property string $category
 * @property integer $is_featured
 * @property integer $is_published
 * @property string $published_at
 * @property integer $view_count
 * @property string $created_by
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 */
abstract class BaseNews extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'news';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'News|News', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('event_id, title', 'required'),
			array('is_featured, is_published, view_count', 'numerical', 'integerOnly'=>true),
			array('title, slug, thumbnail', 'length', 'max'=>255),
			array('category', 'length', 'max'=>50),
			array('created_by', 'length', 'max'=>100),
			array('event_id, category_id, excerpt, content, published_at, created_by, created_at, updated_at, deleted_at', 'safe'),
			array('slug, excerpt, content, thumbnail, category_id, is_featured, is_published, published_at, view_count, created_by, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, title, slug, excerpt, content, thumbnail, category_id, category, is_featured, is_published, published_at, view_count, created_by, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => Yii::t('app', 'Sự kiện'),
			'title' => Yii::t('app', 'Tiêu đề'),
			'slug' => Yii::t('app', 'Đường dẫn (slug)'),
			'excerpt' => Yii::t('app', 'Tóm tắt'),
			'content' => Yii::t('app', 'Nội dung'),
			'thumbnail' => Yii::t('app', 'Ảnh đại diện'),
			'category_id' => Yii::t('app', 'Danh mục'),
			'category' => Yii::t('app', 'Loại tin'),
			'is_featured' => Yii::t('app', 'Tin nổi bật'),
			'is_published' => Yii::t('app', 'Xuất bản'),
			'published_at' => Yii::t('app', 'Ngày xuất bản'),
			'view_count' => Yii::t('app', 'Lượt xem'),
			'created_by' => Yii::t('app', 'Người tạo'),
			'created_at' => Yii::t('app', 'Ngày tạo'),
			'updated_at' => Yii::t('app', 'Ngày cập nhật'),
			'deleted_at' => Yii::t('app', 'Ngày xóa'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('category_id', $this->category_id, true);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('is_featured', $this->is_featured);
		$criteria->compare('is_published', $this->is_published);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
