<?php

/**
 * This is the model base class for the table "competition_rounds".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompetitionRounds".
 *
 * Columns in table "competition_rounds" available as properties of the model,
 * followed by relations of table "competition_rounds" available as properties of the model.
 *
 * @property string $id
 * @property string $competition_id
 * @property string $name
 * @property integer $round_order
 * @property string $location
 * @property string $start_time
 * @property string $end_time
 * @property string $instructions
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property CompetitionRoundResults[] $competitionRoundResults
 * @property Competitions $competition
 */
abstract class BaseCompetitionRounds extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'competition_rounds';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompetitionRounds|CompetitionRounds', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('competition_id, name', 'required'),
			array('round_order', 'numerical', 'integerOnly'=>true),
			array('competition_id', 'length', 'max'=>20),
			array('name, location', 'length', 'max'=>255),
			array('start_time, end_time', 'length', 'max'=>10),
			array('instructions, created_at, updated_at, deleted_at', 'safe'),
			array('round_order, location, start_time, end_time, instructions, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, competition_id, name, round_order, location, start_time, end_time, instructions, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'competitionRoundResults' => array(self::HAS_MANY, 'CompetitionRoundResults', 'round_id'),
			'competition' => array(self::BELONGS_TO, 'Competitions', 'competition_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'competition_id' => null,
			'name' => Yii::t('app', 'Name'),
			'round_order' => Yii::t('app', 'Round Order'),
			'location' => Yii::t('app', 'Location'),
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
			'instructions' => Yii::t('app', 'Instructions'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'competitionRoundResults' => null,
			'competition' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('competition_id', $this->competition_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('round_order', $this->round_order);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('end_time', $this->end_time, true);
		$criteria->compare('instructions', $this->instructions, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}