<?php

/**
 * This is the model base class for the table "alliances".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Alliances".
 *
 * Columns in table "alliances" available as properties of the model,
 * followed by relations of table "alliances" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $org_a_id
 * @property string $org_b_id
 * @property string $request_id
 * @property integer $status
 * @property string $confirmed_at
 * @property string $dissolved_at
 * @property string $dissolved_by
 * @property string $dissolved_reason
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Events $event
 * @property Properties $orgA
 * @property Properties $orgB
 */
abstract class BaseAlliances extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'alliances';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Alliances|Alliances', $n);
	}

	public static function representingColumn() {
		return 'dissolved_reason';
	}

	public function rules() {
		return array(
			array('event_id, org_a_id, org_b_id', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('event_id, org_a_id, org_b_id, request_id', 'length', 'max'=>20),
			array('confirmed_at, dissolved_at, dissolved_by', 'length', 'max'=>10),
			array('dissolved_reason, note, created_at, updated_at, deleted_at', 'safe'),
			array('request_id, status, confirmed_at, dissolved_at, dissolved_by, dissolved_reason, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, org_a_id, org_b_id, request_id, status, confirmed_at, dissolved_at, dissolved_by, dissolved_reason, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'orgA' => array(self::BELONGS_TO, 'Properties', 'org_a_id'),
			'orgB' => array(self::BELONGS_TO, 'Properties', 'org_b_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'org_a_id' => null,
			'org_b_id' => null,
			'request_id' => Yii::t('app', 'Request'),
			'status' => Yii::t('app', 'Status'),
			'confirmed_at' => Yii::t('app', 'Confirmed At'),
			'dissolved_at' => Yii::t('app', 'Dissolved At'),
			'dissolved_by' => Yii::t('app', 'Dissolved By'),
			'dissolved_reason' => Yii::t('app', 'Dissolved Reason'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'event' => null,
			'orgA' => null,
			'orgB' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('org_a_id', $this->org_a_id);
		$criteria->compare('org_b_id', $this->org_b_id);
		$criteria->compare('request_id', $this->request_id, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('confirmed_at', $this->confirmed_at, true);
		$criteria->compare('dissolved_at', $this->dissolved_at, true);
		$criteria->compare('dissolved_by', $this->dissolved_by, true);
		$criteria->compare('dissolved_reason', $this->dissolved_reason, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}