<?php

/**
 * This is the model base class for the table "news_categories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewsCategories".
 *
 * Columns in table "news_categories" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $name
 * @property string $slug
 * @property string $icon
 * @property string $color
 * @property string $description
 * @property integer $sort_order
 * @property integer $is_active
 * @property string $created_at
 * @property string $updated_at
 *
 */
abstract class BaseNewsCategories extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'news_categories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'News Category|News Categories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('event_id, name', 'required'),
			array('sort_order, is_active', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('slug', 'length', 'max'=>100),
			array('icon', 'length', 'max'=>50),
			array('color', 'length', 'max'=>20),
			array('description, created_at, updated_at', 'safe'),
			array('slug, icon, color, description, sort_order, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, name, slug, icon, color, description, sort_order, is_active, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => Yii::t('app', 'Sự kiện'),
			'name' => Yii::t('app', 'Tên danh mục'),
			'slug' => Yii::t('app', 'Đường dẫn (slug)'),
			'icon' => Yii::t('app', 'Biểu tượng'),
			'color' => Yii::t('app', 'Màu sắc'),
			'description' => Yii::t('app', 'Mô tả'),
			'sort_order' => Yii::t('app', 'Thứ tự'),
			'is_active' => Yii::t('app', 'Kích hoạt'),
			'created_at' => Yii::t('app', 'Ngày tạo'),
			'updated_at' => Yii::t('app', 'Ngày cập nhật'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('is_active', $this->is_active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
