<?php

/**
 * This is the model base class for the table "sport_matches".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportMatches".
 *
 * Columns in table "sport_matches" available as properties of the model,
 * followed by relations of table "sport_matches" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $sport_id
 * @property string $stage_id
 * @property string $code
 * @property string $round
 * @property string $match_type
 * @property string $description
 * @property integer $match_order
 * @property string $team_a_id
 * @property string $team_b_id
 * @property string $match_time
 * @property string $location
 * @property string $final_score
 * @property string $note
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property SportMatchResults[] $sportMatchResults
 * @property Events $event
 * @property Sports $sport
 * @property SportStages $stage
 * @property SportTeams $teamA
 * @property SportTeams $teamB
 */
abstract class BaseSportMatches extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_matches';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportMatches|SportMatches', $n);
	}

	public static function representingColumn() {
		return 'match_type';
	}

	public function rules() {
		return array(
			array('sport_id, stage_id', 'required'),
			array('match_order', 'numerical', 'integerOnly'=>true),
			array('event_id, sport_id, stage_id, team_a_id, team_b_id', 'length', 'max'=>20),
			array('code', 'length', 'max'=>50),
			array('round', 'length', 'max'=>100),
			array('match_type', 'length', 'max'=>8),
			array('location, final_score', 'length', 'max'=>255),
			array('status', 'length', 'max'=>9),
			array('description, match_time, note, created_at, updated_at, deleted_at', 'safe'),
			array('event_id, code, round, match_type, description, match_order, team_a_id, team_b_id, match_time, location, final_score, note, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, sport_id, stage_id, code, round, match_type, description, match_order, team_a_id, team_b_id, match_time, location, final_score, note, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sportMatchResults' => array(self::HAS_MANY, 'SportMatchResults', 'match_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'sport' => array(self::BELONGS_TO, 'Sports', 'sport_id'),
			'stage' => array(self::BELONGS_TO, 'SportStages', 'stage_id'),
			'teamA' => array(self::BELONGS_TO, 'SportTeams', 'team_a_id'),
			'teamB' => array(self::BELONGS_TO, 'SportTeams', 'team_b_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'sport_id' => null,
			'stage_id' => null,
			'code' => Yii::t('app', 'Code'),
			'round' => Yii::t('app', 'Round'),
			'match_type' => Yii::t('app', 'Match Type'),
			'description' => Yii::t('app', 'Description'),
			'match_order' => Yii::t('app', 'Match Order'),
			'team_a_id' => null,
			'team_b_id' => null,
			'match_time' => Yii::t('app', 'Match Time'),
			'location' => Yii::t('app', 'Location'),
			'final_score' => Yii::t('app', 'Final Score'),
			'note' => Yii::t('app', 'Note'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'sportMatchResults' => null,
			'event' => null,
			'sport' => null,
			'stage' => null,
			'teamA' => null,
			'teamB' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('sport_id', $this->sport_id);
		$criteria->compare('stage_id', $this->stage_id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('round', $this->round, true);
		$criteria->compare('match_type', $this->match_type, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('match_order', $this->match_order);
		$criteria->compare('team_a_id', $this->team_a_id);
		$criteria->compare('team_b_id', $this->team_b_id);
		$criteria->compare('match_time', $this->match_time, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('final_score', $this->final_score, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}