<?php

/**
 * This is the model base class for the table "registrations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Registrations".
 *
 * Columns in table "registrations" available as properties of the model,
 * followed by relations of table "registrations" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $property_id
 * @property string $relation_property_id
 * @property string $period_id
 * @property string $submitted_by
 * @property string $status
 * @property string $document
 * @property string $submitted_at
 * @property string $reviewed_by
 * @property string $reviewed_at
 * @property string $rejection_reason
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees[] $attendees
 * @property RegistrationDetails[] $registrationDetails
 * @property Events $event
 * @property RegistrationPeriods $period
 * @property Properties $property
 * @property Properties $relationProperty
 */
abstract class BaseRegistrations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'registrations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Registrations|Registrations', $n);
	}

	public static function representingColumn() {
		return 'status';
	}

	public function rules() {
		return array(
			array('property_id, period_id, submitted_by', 'required'),
			array('event_id, property_id, relation_property_id, period_id, submitted_by', 'length', 'max'=>20),
			array('status', 'length', 'max'=>9),
			array('document', 'length', 'max'=>500),
			array('submitted_at, reviewed_by, reviewed_at', 'length', 'max'=>10),
			array('rejection_reason, note, created_at, updated_at, deleted_at', 'safe'),
			array('event_id, relation_property_id, status, document, submitted_at, reviewed_by, reviewed_at, rejection_reason, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, property_id, relation_property_id, period_id, submitted_by, status, document, submitted_at, reviewed_by, reviewed_at, rejection_reason, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendees' => array(self::HAS_MANY, 'Attendees', 'registration_id'),
			'registrationDetails' => array(self::HAS_MANY, 'RegistrationDetails', 'registration_id'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'period' => array(self::BELONGS_TO, 'RegistrationPeriods', 'period_id'),
			'property' => array(self::BELONGS_TO, 'Properties', 'property_id'),
			'relationProperty' => array(self::BELONGS_TO, 'Properties', 'relation_property_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'property_id' => null,
			'relation_property_id' => null,
			'period_id' => null,
			'submitted_by' => Yii::t('app', 'Submitted By'),
			'status' => Yii::t('app', 'Status'),
			'document' => Yii::t('app', 'Document'),
			'submitted_at' => Yii::t('app', 'Submitted At'),
			'reviewed_by' => Yii::t('app', 'Reviewed By'),
			'reviewed_at' => Yii::t('app', 'Reviewed At'),
			'rejection_reason' => Yii::t('app', 'Rejection Reason'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendees' => null,
			'registrationDetails' => null,
			'event' => null,
			'period' => null,
			'property' => null,
			'relationProperty' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('property_id', $this->property_id);
		$criteria->compare('relation_property_id', $this->relation_property_id);
		$criteria->compare('period_id', $this->period_id);
		$criteria->compare('submitted_by', $this->submitted_by, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('document', $this->document, true);
		$criteria->compare('submitted_at', $this->submitted_at, true);
		$criteria->compare('reviewed_by', $this->reviewed_by, true);
		$criteria->compare('reviewed_at', $this->reviewed_at, true);
		$criteria->compare('rejection_reason', $this->rejection_reason, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}