<?php

/**
 * This is the model base class for the table "competition_registrations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompetitionRegistrations".
 *
 * Columns in table "competition_registrations" available as properties of the model,
 * followed by relations of table "competition_registrations" available as properties of the model.
 *
 * @property string $id
 * @property string $competition_id
 * @property string $attendee_id
 * @property string $candidate_number
 * @property integer $status
 * @property string $registered_at
 * @property string $confirmed_by
 * @property string $confirmed_at
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property Competitions $competition
 * @property CompetitionRoundResults[] $competitionRoundResults
 */
abstract class BaseCompetitionRegistrations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'competition_registrations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompetitionRegistrations|CompetitionRegistrations', $n);
	}

	public static function representingColumn() {
		return 'candidate_number';
	}

	public function rules() {
		return array(
			array('competition_id, attendee_id', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('competition_id, attendee_id, candidate_number, confirmed_by', 'length', 'max'=>20),
			array('registered_at, confirmed_at, note, created_at, updated_at, deleted_at', 'safe'),
			array('candidate_number, status, registered_at, confirmed_by, confirmed_at, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, competition_id, attendee_id, candidate_number, status, registered_at, confirmed_by, confirmed_at, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'competition' => array(self::BELONGS_TO, 'Competitions', 'competition_id'),
			'competitionRoundResults' => array(self::HAS_MANY, 'CompetitionRoundResults', 'registration_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'competition_id' => null,
			'attendee_id' => null,
			'candidate_number' => Yii::t('app', 'Candidate Number'),
			'status' => Yii::t('app', 'Status'),
			'registered_at' => Yii::t('app', 'Registered At'),
			'confirmed_by' => Yii::t('app', 'Confirmed By'),
			'confirmed_at' => Yii::t('app', 'Confirmed At'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'competition' => null,
			'competitionRoundResults' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('competition_id', $this->competition_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('candidate_number', $this->candidate_number, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('registered_at', $this->registered_at, true);
		$criteria->compare('confirmed_by', $this->confirmed_by, true);
		$criteria->compare('confirmed_at', $this->confirmed_at, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}