<?php

/**
 * This is the model base class for the table "sport_team_members".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportTeamMembers".
 *
 * Columns in table "sport_team_members" available as properties of the model,
 * followed by relations of table "sport_team_members" available as properties of the model.
 *
 * @property string $id
 * @property string $sport_team_id
 * @property string $attendee_id
 * @property string $code
 * @property string $name
 * @property string $image
 * @property string $jersey_number
 * @property string $position
 * @property integer $is_captain
 * @property string $note
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Attendees $attendee
 * @property SportTeams $sportTeam
 */
abstract class BaseSportTeamMembers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_team_members';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportTeamMembers|SportTeamMembers', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('sport_team_id, attendee_id, code', 'required'),
			array('is_captain, status', 'numerical', 'integerOnly'=>true),
			array('sport_team_id, attendee_id', 'length', 'max'=>20),
			array('code, position', 'length', 'max'=>100),
			array('name', 'length', 'max'=>255),
			array('image', 'length', 'max'=>500),
			array('jersey_number', 'length', 'max'=>10),
			array('note, created_at, updated_at, deleted_at', 'safe'),
			array('name, image, jersey_number, position, is_captain, note, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, sport_team_id, attendee_id, code, name, image, jersey_number, position, is_captain, note, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'attendee' => array(self::BELONGS_TO, 'Attendees', 'attendee_id'),
			'sportTeam' => array(self::BELONGS_TO, 'SportTeams', 'sport_team_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sport_team_id' => null,
			'attendee_id' => null,
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'image' => Yii::t('app', 'Image'),
			'jersey_number' => Yii::t('app', 'Jersey Number'),
			'position' => Yii::t('app', 'Position'),
			'is_captain' => Yii::t('app', 'Is Captain'),
			'note' => Yii::t('app', 'Note'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'attendee' => null,
			'sportTeam' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('sport_team_id', $this->sport_team_id);
		$criteria->compare('attendee_id', $this->attendee_id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('jersey_number', $this->jersey_number, true);
		$criteria->compare('position', $this->position, true);
		$criteria->compare('is_captain', $this->is_captain);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}