<?php

/**
 * This is the model base class for the table "alliance_requests".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AllianceRequests".
 *
 * Columns in table "alliance_requests" available as properties of the model,
 * followed by relations of table "alliance_requests" available as properties of the model.
 *
 * @property string $id
 * @property string $event_id
 * @property string $requester_org_id
 * @property string $target_org_id
 * @property integer $status
 * @property string $requested_by
 * @property string $requested_at
 * @property string $reviewed_by
 * @property string $reviewed_at
 * @property string $rejection_reason
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property Events $event
 * @property Properties $requesterOrg
 * @property Properties $targetOrg
 */
abstract class BaseAllianceRequests extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'alliance_requests';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AllianceRequests|AllianceRequests', $n);
	}

	public static function representingColumn() {
		return 'requested_at';
	}

	public function rules() {
		return array(
			array('event_id, requester_org_id, target_org_id', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('event_id, requester_org_id, target_org_id, requested_by, reviewed_by', 'length', 'max'=>20),
			array('requested_at, reviewed_at, rejection_reason, note, created_at, updated_at, deleted_at', 'safe'),
			array('status, requested_by, requested_at, reviewed_by, reviewed_at, rejection_reason, note, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, requester_org_id, target_org_id, status, requested_by, requested_at, reviewed_by, reviewed_at, rejection_reason, note, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
			'requesterOrg' => array(self::BELONGS_TO, 'Properties', 'requester_org_id'),
			'targetOrg' => array(self::BELONGS_TO, 'Properties', 'target_org_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'requester_org_id' => null,
			'target_org_id' => null,
			'status' => Yii::t('app', 'Status'),
			'requested_by' => Yii::t('app', 'Requested By'),
			'requested_at' => Yii::t('app', 'Requested At'),
			'reviewed_by' => Yii::t('app', 'Reviewed By'),
			'reviewed_at' => Yii::t('app', 'Reviewed At'),
			'rejection_reason' => Yii::t('app', 'Rejection Reason'),
			'note' => Yii::t('app', 'Note'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'event' => null,
			'requesterOrg' => null,
			'targetOrg' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('requester_org_id', $this->requester_org_id);
		$criteria->compare('target_org_id', $this->target_org_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('requested_by', $this->requested_by, true);
		$criteria->compare('requested_at', $this->requested_at, true);
		$criteria->compare('reviewed_by', $this->reviewed_by, true);
		$criteria->compare('reviewed_at', $this->reviewed_at, true);
		$criteria->compare('rejection_reason', $this->rejection_reason, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}