<?php

/**
 * This is the model base class for the table "m_config".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MConfig".
 *
 * Columns in table "m_config" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $hotline
 * @property string $title
 * @property string $logo
 * @property string $favicon
 * @property string $facebook
 * @property string $google
 * @property string $youtube
 * @property string $tam_nhin
 * @property string $su_menh
 * @property string $gioi_thieu
 * @property string $lich_su
 * @property string $phat_trien
 * @property string $thuong_hieu
 * @property string $chan_thanh
 * @property string $cam_ket
 * @property string $can_bang
 * @property string $ton_trong
 * @property string $thich_ung
 * @property string $thong_nhat
 * @property string $chinh_sach_nld
 * @property string $van_hoa
 * @property string $iframe_gioithieu
 * @property string $iframe_lichsu
 * @property string $top_background
 * @property string $email_username
 * @property string $email_pass
 * @property string $footer_description
 *
 */
abstract class BaseMConfig extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'm_config';
    }

    public static function representingColumn()
    {
        return 'hotline';
    }

    public function rules()
    {
        return array(
            array('hotline, title, logo, favicon', 'required'),
            array('hotline, title, facebook, google, youtube, top_background, email_username, email_pass', 'length', 'max' => 255),
            array('logo, favicon', 'length', 'max' => 500),
            array('tam_nhin, su_menh, gioi_thieu, lich_su, phat_trien, thuong_hieu, chan_thanh, cam_ket, can_bang, ton_trong, thich_ung, thong_nhat, chinh_sach_nld, van_hoa, iframe_gioithieu, iframe_lichsu', 'safe'),
            array('facebook, google, youtube, tam_nhin, su_menh, gioi_thieu, lich_su, phat_trien, thuong_hieu, chan_thanh, cam_ket, can_bang, ton_trong, thich_ung, thong_nhat, chinh_sach_nld, van_hoa, iframe_gioithieu, iframe_lichsu, top_background, email_username, email_pass, footer_description', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, hotline, title, logo, favicon, facebook, google, youtube, tam_nhin, su_menh, gioi_thieu, lich_su, phat_trien, thuong_hieu, chan_thanh, cam_ket, can_bang, ton_trong, thich_ung, thong_nhat, chinh_sach_nld, van_hoa, iframe_gioithieu, iframe_lichsu, top_background, email_username, email_pass, footer_description', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array();
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'hotline' => Yii::t('app', 'Hotline'),
            'title' => Yii::t('app', 'Title'),
            'logo' => Yii::t('app', 'Logo'),
            'favicon' => Yii::t('app', 'Favicon'),
            'facebook' => Yii::t('app', 'Facebook'),
            'google' => Yii::t('app', 'Google'),
            'youtube' => Yii::t('app', 'Youtube'),
            'tam_nhin' => Yii::t('app', 'Tầm nhìn'),
            'su_menh' => Yii::t('app', 'Sứ mệnh'),
            'gioi_thieu' => Yii::t('app', 'Giới thiệu'),
            'lich_su' => Yii::t('app', 'Lịch sử'),
            'phat_trien' => Yii::t('app', 'Phát triển'),
            'thuong_hieu' => Yii::t('app', 'Thương hiệu'),
            'chan_thanh' => Yii::t('app', 'Chân thành'),
            'cam_ket' => Yii::t('app', 'Cam kết'),
            'can_bang' => Yii::t('app', 'Cân bằng'),
            'ton_trong' => Yii::t('app', 'Tôn trọng'),
            'thich_ung' => Yii::t('app', 'Thích ứng'),
            'thong_nhat' => Yii::t('app', 'Thống nhất'),
            'chinh_sach_nld' => Yii::t('app', 'Chính sách người lao động'),
            'van_hoa' => Yii::t('app', 'Văn hóa'),
            'iframe_gioithieu' => Yii::t('app', 'Iframe giới thiệu'),
            'iframe_lichsu' => Yii::t('app', 'Iframe Lịch sử'),
            'top_background' => Yii::t('app', 'Ảnh nền trên cùng'),
            'footer_description' => Yii::t('app', 'Giới thiệu dưới Footer'),
            'count_now_cp' => Yii::t('app', 'Tổng số cổ phần biểu quyết đang lưu hành của OCH'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('hotline', $this->hotline, true);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('logo', $this->logo, true);
        $criteria->compare('favicon', $this->favicon, true);
        $criteria->compare('facebook', $this->facebook, true);
        $criteria->compare('google', $this->google, true);
        $criteria->compare('youtube', $this->youtube, true);
        $criteria->compare('tam_nhin', $this->tam_nhin, true);
        $criteria->compare('su_menh', $this->su_menh, true);
        $criteria->compare('gioi_thieu', $this->gioi_thieu, true);
        $criteria->compare('lich_su', $this->lich_su, true);
        $criteria->compare('phat_trien', $this->phat_trien, true);
        $criteria->compare('thuong_hieu', $this->thuong_hieu, true);
        $criteria->compare('chan_thanh', $this->chan_thanh, true);
        $criteria->compare('cam_ket', $this->cam_ket, true);
        $criteria->compare('can_bang', $this->can_bang, true);
        $criteria->compare('ton_trong', $this->ton_trong, true);
        $criteria->compare('thich_ung', $this->thich_ung, true);
        $criteria->compare('thong_nhat', $this->thong_nhat, true);
        $criteria->compare('chinh_sach_nld', $this->chinh_sach_nld, true);
        $criteria->compare('van_hoa', $this->van_hoa, true);
        $criteria->compare('iframe_gioithieu', $this->iframe_gioithieu, true);
        $criteria->compare('iframe_lichsu', $this->iframe_lichsu, true);
        $criteria->compare('top_background', $this->top_background, true);
        $criteria->compare('email_username', $this->email_username, true);
        $criteria->compare('email_pass', $this->email_pass, true);
        $criteria->compare('footer_description', $this->footer_description, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}