<?php

/**
 * This is the model base class for the table "meal_tables".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MealTables".
 *
 * Columns in table "meal_tables" available as properties of the model,
 * followed by relations of table "meal_tables" available as properties of the model.
 *
 * @property string $id
 * @property string $meal_id
 * @property string $name
 * @property integer $capacity
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property MealAttendees[] $mealAttendees
 * @property Meals $meal
 */
abstract class BaseMealTables extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'meal_tables';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MealTables|MealTables', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('meal_id, name', 'required'),
			array('capacity, status', 'numerical', 'integerOnly'=>true),
			array('meal_id', 'length', 'max'=>20),
			array('name', 'length', 'max'=>100),
			array('created_at, updated_at, deleted_at', 'safe'),
			array('capacity, status, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, meal_id, name, capacity, status, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mealAttendees' => array(self::HAS_MANY, 'MealAttendees', 'table_id'),
			'meal' => array(self::BELONGS_TO, 'Meals', 'meal_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'meal_id' => null,
			'name' => Yii::t('app', 'Name'),
			'capacity' => Yii::t('app', 'Capacity'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'mealAttendees' => null,
			'meal' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('meal_id', $this->meal_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('capacity', $this->capacity);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}