<?php

/**
 * This is the model base class for the table "talent_entries".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TalentEntries".
 *
 * Columns in table "talent_entries" available as properties of the model,
 * followed by relations of table "talent_entries" available as properties of the model.
 *
 * @property string $id
 * @property string $show_id
 * @property string $category_id
 * @property string $property_id
 * @property string $title
 * @property string $description
 * @property integer $duration_seconds
 * @property string $music_path
 * @property string $video_path
 * @property integer $performance_order
 * @property string $status
 * @property double $final_score
 * @property integer $final_rank
 * @property string $award
 * @property string $note
 * @property string $submitted_at
 * @property string $approved_by
 * @property string $approved_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 * @property TalentCategories $category
 * @property Properties $property
 * @property TalentShows $show
 * @property TalentEntryMembers[] $talentEntryMembers
 * @property TalentScores[] $talentScores
 */
abstract class BaseTalentEntries extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'talent_entries';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TalentEntries|TalentEntries', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('show_id, category_id, property_id, title', 'required'),
			array('duration_seconds, performance_order, final_rank', 'numerical', 'integerOnly'=>true),
			array('final_score', 'numerical'),
			array('show_id, category_id, property_id, approved_by', 'length', 'max'=>20),
			array('title, award', 'length', 'max'=>255),
			array('music_path, video_path', 'length', 'max'=>500),
			array('status', 'length', 'max'=>9),
			array('description, note, submitted_at, approved_at, created_at, updated_at, deleted_at', 'safe'),
			array('description, duration_seconds, music_path, video_path, performance_order, status, final_score, final_rank, award, note, submitted_at, approved_by, approved_at, created_at, updated_at, deleted_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, show_id, category_id, property_id, title, description, duration_seconds, music_path, video_path, performance_order, status, final_score, final_rank, award, note, submitted_at, approved_by, approved_at, created_at, updated_at, deleted_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'TalentCategories', 'category_id'),
			'property' => array(self::BELONGS_TO, 'Properties', 'property_id'),
			'show' => array(self::BELONGS_TO, 'TalentShows', 'show_id'),
			'talentEntryMembers' => array(self::HAS_MANY, 'TalentEntryMembers', 'entry_id'),
			'talentScores' => array(self::HAS_MANY, 'TalentScores', 'entry_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'show_id' => null,
			'category_id' => null,
			'property_id' => null,
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'duration_seconds' => Yii::t('app', 'Duration Seconds'),
			'music_path' => Yii::t('app', 'Music Path'),
			'video_path' => Yii::t('app', 'Video Path'),
			'performance_order' => Yii::t('app', 'Performance Order'),
			'status' => Yii::t('app', 'Status'),
			'final_score' => Yii::t('app', 'Final Score'),
			'final_rank' => Yii::t('app', 'Final Rank'),
			'award' => Yii::t('app', 'Award'),
			'note' => Yii::t('app', 'Note'),
			'submitted_at' => Yii::t('app', 'Submitted At'),
			'approved_by' => Yii::t('app', 'Approved By'),
			'approved_at' => Yii::t('app', 'Approved At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deleted_at' => Yii::t('app', 'Deleted At'),
			'category' => null,
			'property' => null,
			'show' => null,
			'talentEntryMembers' => null,
			'talentScores' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('show_id', $this->show_id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('property_id', $this->property_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('duration_seconds', $this->duration_seconds);
		$criteria->compare('music_path', $this->music_path, true);
		$criteria->compare('video_path', $this->video_path, true);
		$criteria->compare('performance_order', $this->performance_order);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('final_score', $this->final_score);
		$criteria->compare('final_rank', $this->final_rank);
		$criteria->compare('award', $this->award, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('submitted_at', $this->submitted_at, true);
		$criteria->compare('approved_by', $this->approved_by, true);
		$criteria->compare('approved_at', $this->approved_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deleted_at', $this->deleted_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}