import os
import shutil
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import qn, nsdecls

# Paths to source images generated by generate_image
SRC_IMAGES = {
    'dashboard': r'C:\Users\DSWM\.gemini\antigravity-ide\brain\861530bf-6ab4-4412-963b-7383a37f7cb5\unit_reg_dashboard_1779936334606.png',
    'badge': r'C:\Users\DSWM\.gemini\antigravity-ide\brain\861530bf-6ab4-4412-963b-7383a37f7cb5\admin_badge_mgmt_1779936357795.png',
    'banquet': r'C:\Users\DSWM\.gemini\antigravity-ide\brain\861530bf-6ab4-4412-963b-7383a37f7cb5\banquet_table_canvas_1779936377544.png',
    'mobile': r'C:\Users\DSWM\.gemini\antigravity-ide\brain\861530bf-6ab4-4412-963b-7383a37f7cb5\mobile_qr_landing_1779936393431.png'
}

DEST_DIR = r'e:\eventregis\docs\images'
os.makedirs(DEST_DIR, exist_ok=True)

# Copy images to permanent workspace docs/images/ folder
IMAGE_PATHS = {}
for key, src in SRC_IMAGES.items():
    dest_name = f"{key}_mockup.png"
    dest_path = os.path.join(DEST_DIR, dest_name)
    if os.path.exists(src):
        shutil.copy2(src, dest_path)
        print(f"Copied {src} -> {dest_path}")
        IMAGE_PATHS[key] = dest_path
    else:
        print(f"Source file not found: {src}")
        IMAGE_PATHS[key] = None

# Custom styling helpers
def set_cell_background(cell, hex_color):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{hex_color}"/>')
    tcPr.append(shd)

def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for m, val in [('top', top), ('bottom', bottom), ('left', left), ('right', right)]:
        node = OxmlElement(f'w:{m}')
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)

def add_heading_styled(doc, text, level, space_before=Pt(12), space_after=Pt(6)):
    heading = doc.add_heading(text, level=level)
    heading.paragraph_format.space_before = space_before
    heading.paragraph_format.space_after = space_after
    heading.paragraph_format.keep_with_next = True
    
    # Apply Mường Thanh Premium Burgundy color to headings
    run = heading.runs[0]
    run.font.name = 'Arial'
    if level == 1:
        run.font.size = Pt(18)
        run.font.color.rgb = RGBColor(139, 0, 0)  # Burgundy
        run.bold = True
    elif level == 2:
        run.font.size = Pt(14)
        run.font.color.rgb = RGBColor(163, 0, 0)
        run.bold = True
    elif level == 3:
        run.font.size = Pt(12)
        run.font.color.rgb = RGBColor(0, 0, 0)
        run.bold = True
        
    return heading

def add_paragraph_styled(doc, text="", style='Normal', space_after=Pt(6), line_spacing=1.15):
    p = doc.add_paragraph(style=style)
    p.paragraph_format.space_after = space_after
    p.paragraph_format.line_spacing = line_spacing
    if text:
        run = p.add_run(text)
        run.font.name = 'Arial'
        run.font.size = Pt(11)
    return p

def add_bullet_item(doc, bold_prefix, text):
    p = doc.add_paragraph(style='List Bullet')
    p.paragraph_format.space_after = Pt(3)
    p.paragraph_format.line_spacing = 1.15
    
    run_bold = p.add_run(bold_prefix)
    run_bold.font.name = 'Arial'
    run_bold.font.size = Pt(11)
    run_bold.bold = True
    
    run_text = p.add_run(text)
    run_text.font.name = 'Arial'
    run_text.font.size = Pt(11)
    return p

def add_callout(doc, text):
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Inches(0.4)
    p.paragraph_format.right_indent = Inches(0.4)
    p.paragraph_format.space_before = Pt(8)
    p.paragraph_format.space_after = Pt(8)
    
    # Shading background XML
    shading = OxmlElement('w:shd')
    shading.set(qn('w:fill'), 'F5F5F5')
    p._p.get_or_add_pPr().append(shading)
    
    # Left border XML
    pBrd = OxmlElement('w:pBrd')
    left_border = OxmlElement('w:left')
    left_border.set(qn('w:val'), 'single')
    left_border.set(qn('w:sz'), '24')  # 3pt width
    left_border.set(qn('w:space'), '8')
    left_border.set(qn('w:color'), '8B0000')  # Burgundy border
    pBrd.append(left_border)
    p._p.get_or_add_pPr().append(pBrd)
    
    run = p.add_run(text)
    run.font.name = 'Arial'
    run.font.size = Pt(10.5)
    run.italic = True
    return p

def add_centered_picture(doc, path, caption, width_in=5.8):
    if not path or not os.path.exists(path):
        add_paragraph_styled(doc, f"[Ảnh minh họa không khả dụng: {path}]", style='Normal')
        return
        
    p_img = doc.add_paragraph()
    p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_img.paragraph_format.space_before = Pt(8)
    p_img.paragraph_format.space_after = Pt(4)
    
    p_img.add_run().add_picture(path, width=Inches(width_in))
    
    p_cap = doc.add_paragraph()
    p_cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_cap.paragraph_format.space_after = Pt(12)
    run_cap = p_cap.add_run(f"Hình minh họa: {caption}")
    run_cap.font.name = 'Arial'
    run_cap.font.size = Pt(9.5)
    run_cap.italic = True
    run_cap.font.color.rgb = RGBColor(128, 128, 128)

def format_grid_table(table, col_widths, headers, data):
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    # Header formatting
    hdr_cells = table.rows[0].cells
    for i, header_text in enumerate(headers):
        hdr_cells[i].text = header_text
        set_cell_background(hdr_cells[i], '8B0000')  # Burgundy Header
        set_cell_margins(hdr_cells[i], top=120, bottom=120, left=150, right=150)
        p = hdr_cells[i].paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = p.runs[0]
        run.font.name = 'Arial'
        run.font.size = Pt(10)
        run.bold = True
        run.font.color.rgb = RGBColor(255, 255, 255)
        
    # Data row formatting
    for r_idx, row_data in enumerate(data):
        row_cells = table.rows[r_idx + 1].cells
        bg_color = 'F9F9F9' if r_idx % 2 == 0 else 'FFFFFF'
        for c_idx, cell_text in enumerate(row_data):
            row_cells[c_idx].text = str(cell_text)
            set_cell_background(row_cells[c_idx], bg_color)
            set_cell_margins(row_cells[c_idx], top=80, bottom=80, left=150, right=150)
            p = row_cells[c_idx].paragraphs[0]
            run = p.runs[0] if p.runs else p.add_run()
            run.font.name = 'Arial'
            run.font.size = Pt(9.5)
            
    # Set cell widths
    for row in table.rows:
        for idx, width in enumerate(col_widths):
            row.cells[idx].width = Inches(width)

# Main document generation
def generate_docx():
    doc = Document()
    
    # Configure margins (1 inch)
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)
        
    # Document Title
    p_title = doc.add_paragraph()
    p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_title.paragraph_format.space_before = Pt(36)
    p_title.paragraph_format.space_after = Pt(6)
    run_title = p_title.add_run("TÀI LIỆU HƯỚNG DẪN SỬ DỤNG")
    run_title.font.name = 'Arial'
    run_title.font.size = Pt(24)
    run_title.font.color.rgb = RGBColor(139, 0, 0)
    run_title.bold = True
    
    p_sub = doc.add_paragraph()
    p_sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_sub.paragraph_format.space_after = Pt(48)
    run_sub = p_sub.add_run("HỆ THỐNG QUẢN LÝ SỰ KIỆN ĐẠI HỘI TẬP TRUNG\n(EVENTREGIS)")
    run_sub.font.name = 'Arial'
    run_sub.font.size = Pt(16)
    run_sub.bold = True
    run_sub.font.color.rgb = RGBColor(100, 100, 100)
    
    add_paragraph_styled(doc, "Phiên bản: 2.0 (Cập nhật mới nhất 2026)").alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_paragraph_styled(doc, "Tech Stack: Yii1 PHP Framework | Nền tảng Portal SSO").alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_page_break()
    
    # Section 1
    add_heading_styled(doc, "1. Tổng Quan Hệ Thống & Phân Quyền Sử Dụng", level=1)
    add_paragraph_styled(doc, "Hệ thống EventRegis được xây dựng nhằm số hóa và quản lý toàn bộ vòng đời của sự kiện đại hội tập trung với quy mô khoảng 600 đại biểu tham dự từ 50-100 khách sạn thành viên và đơn vị trực thuộc. Hệ thống cung cấp giải pháp khép kín từ đăng ký trực tuyến, kiểm duyệt hồ sơ đại biểu, in thẻ tích hợp mã QR, phân bố sơ đồ tiệc, quản lý thi đấu thể thao chuyên nghiệp và hỗ trợ người tham dự tra cứu lịch trình cá nhân hóa qua quét QR.")
    
    add_paragraph_styled(doc, "Dưới đây là bảng phân quyền chi tiết các tài khoản (Actors) trên hệ thống:")
    
    # Table 1: Actor Permissions
    table_actors = doc.add_table(rows=6, cols=3)
    headers_actors = ["Vai trò (Actor)", "Tài khoản đăng nhập", "Quyền hạn & Nghiệp vụ chính"]
    col_widths_actors = [1.8, 1.8, 3.4]
    data_actors = [
        ["Đại diện Đơn vị", "Tài khoản đơn vị (unit_accounts)", "Đăng ký tham gia hoạt động, gửi/duyệt liên quân nội dung, điền danh sách đại biểu, tải giấy tờ cá nhân, ghép đội thi đấu."],
        ["Nhân sự HO (HR)", "Tài khoản nội bộ (users - role=hr)", "Duyệt/từ chối phiếu đăng ký đại biểu của đơn vị, kiểm tra hợp lệ hồ sơ giấy tờ, gán vai trò sự kiện, chỉ định Trưởng đoàn."],
        ["Admin HO", "Tài khoản quản trị (users - role=admin)", "Toàn quyền hệ thống, cấu hình đợt đăng ký, thiết lập số môn thể thao tối đa, quản lý in thẻ hàng loạt, quản lý cấu hình các BTC chuyên môn."],
        ["Trưởng đoàn", "Tài khoản Đại biểu (có flag is_team_lead)", "Xem danh sách đoàn, báo cắt suất ăn từng người hoặc cắt hàng loạt cho cả đoàn trước giờ khóa sổ (Cutoff Time)."],
        ["BTC Chuyên môn (Thi nghiệp vụ / Thể thao / Tiệc)", "Tài khoản nội bộ (users - role=competition/sports/banquet)", "Quản lý cuộc thi/môn thể thao, xếp lịch thi đấu, cập nhật tỉ số live, thiết kế sơ đồ bàn tiệc kéo thả và xếp chỗ đại biểu."]
    ]
    format_grid_table(table_actors, col_widths_actors, headers_actors, data_actors)
    
    # Section 2
    add_heading_styled(doc, "2. Hướng Dẫn Dành Cho Đại Diện Đơn Vị", level=1)
    add_paragraph_styled(doc, "Tài khoản Đại diện Đơn vị chịu trách nhiệm thực hiện đăng ký thông tin cho đơn vị mình tham gia đại hội thông qua quy trình 4 bước tuần tự:")
    
    add_heading_styled(doc, "Bước 2.1: Đăng nhập & Thiết lập Liên quân theo từng Nội dung (Content-level Alliance)", level=2)
    add_paragraph_styled(doc, "Liên quân không áp dụng chung cho cả sự kiện mà được chọn riêng biệt cho từng nội dung/môn thi đấu tùy thuộc vào nhân sự thực tế của đơn vị. Một đơn vị chỉ được phép liên quân tối đa với số lượng đơn vị khác được cấu hình cho mỗi nội dung (event_contents.max_alliance_orgs).")
    
    add_bullet_item(doc, "Gửi yêu cầu liên quân: ", "Đăng nhập -> Vào tab 'Liên quân' -> Click 'Gửi yêu cầu liên quân' -> Chọn đơn vị đối tác trong danh sách và nội dung đăng ký (VD: Bóng đá nam) -> Click 'Gửi'. Hệ thống lưu trạng thái là 'Chờ duyệt' (pending).")
    add_bullet_item(doc, "Duyệt yêu cầu liên quân: ", "Khi nhận được yêu cầu liên quân từ đơn vị khác, hệ thống hiển thị thông báo. Đại diện đơn vị có quyền click 'Chấp nhận' để kích hoạt trạng thái liên quân 'Hoạt động' (active) hoặc 'Từ chối' kèm lý do.")
    
    add_heading_styled(doc, "Bước 2.2: Nhập danh sách Đại biểu & Upload giấy tờ bắt buộc", level=2)
    add_paragraph_styled(doc, "Trước khi đăng ký thể thao và thi nghiệp vụ, đơn vị phải tạo danh sách Đại biểu tham gia sự kiện. Để thực hiện, chọn menu 'Danh sách Đại biểu' -> Click 'Thêm người tham dự' và tiến hành các thao tác:")
    
    add_bullet_item(doc, "Chọn từ Danh sách Nhân viên: ", "Hệ thống hỗ trợ đồng bộ danh sách nhân viên từ hệ thống SMILE. Người dùng chỉ cần gõ tìm kiếm, hệ thống sẽ tự động điền các thông tin cơ bản: Họ tên, Chức danh, Phòng ban. Lưu ý quy định nghiệp vụ đặc biệt: Hệ thống chỉ hiển thị và cho phép đăng ký những nhân viên có ngày gia nhập đơn vị trước ngày 01/06/2026. Những nhân viên có ngày gia nhập từ ngày 01/06/2026 trở đi sẽ bị hệ thống tự động ẩn để đảm bảo tính công bằng. Trường hợp nhân viên chưa có trên SMILE nhưng thỏa mãn điều kiện thời gian gia nhập, người dùng tích chọn 'Tự điền thông tin' để tự nhập.")
    add_bullet_item(doc, "Tải lên 4 Giấy tờ bắt buộc: ", "Đối với mỗi đại biểu, bắt buộc phải cung cấp đủ hồ sơ pháp lý:")
    doc.add_paragraph("- Ảnh mặt trước CCCD (định dạng JPG/PNG, dung lượng tối đa 5MB).", style='List Bullet')
    doc.add_paragraph("- Ảnh mặt sau CCCD (định dạng JPG/PNG, dung lượng tối đa 5MB).", style='List Bullet')
    doc.add_paragraph("- Ảnh chân dung in thẻ (định dạng JPG/PNG, dung lượng tối đa 5MB) - Lưu ý bắt buộc ảnh phải có kích thước chính xác 530x530 pixel, nếu không hệ thống sẽ báo lỗi validation và từ chối lưu hồ sơ.", style='List Bullet')
    doc.add_paragraph("- Scan Hợp đồng lao động ký với đơn vị (định dạng PDF hoặc JPG, tối đa 10MB).", style='List Bullet')
    
    add_callout(doc, "Lưu ý quan trọng: Quy tắc validate ảnh chân dung 530x530px hoạt động ở phía máy chủ. Ảnh chân dung cần rõ nét, phông nền sáng, không đội mũ để phục vụ in thẻ đại biểu vật lý.")
    
    add_centered_picture(doc, IMAGE_PATHS['dashboard'], "Giao diện Đăng ký Đại biểu đơn vị, chọn nhân viên từ SMILE, upload hồ sơ và thiết lập liên quân", width_in=5.8)
    
    add_heading_styled(doc, "Bước 2.3: Đăng ký tham gia hoạt động (Event Registration)", level=2)
    add_paragraph_styled(doc, "Sau khi hoàn thiện danh sách đại biểu, Đại diện đơn vị đăng ký hoạt động tham gia sự kiện:")
    add_bullet_item(doc, "Đăng ký theo số lượng (Quantity-based): ", "Áp dụng cho các môn thể thao tập thể (VD: Bóng đá, Kéo co, Cầu lông...). Đơn vị chỉ chọn đăng ký tham gia và số lượng đội tham gia (Ví dụ: Đăng ký tham gia Bóng đá nam - 2 đội). Chưa cần khai báo tên thành viên chi tiết ở bước này.")
    add_bullet_item(doc, "Đăng ký danh sách cụ thể (Detailed-based): ", "Áp dụng cho các nội dung cá nhân như Thi nghiệp vụ, Miss, Văn nghệ. Đơn vị phải gán trực tiếp đại biểu cụ thể trong danh sách đại biểu đã tạo vào nội dung thi đấu ngay tại màn hình đăng ký.")
    
    add_heading_styled(doc, "Bước 2.4: Tạo đội & Ghép thành viên liên quân (Create Teams)", level=2)
    add_paragraph_styled(doc, "Sau khi phiếu đăng ký được phê duyệt bởi HR HO, đơn vị bắt đầu thiết lập thành viên chi tiết cho các môn thể thao tập thể đã đăng ký ở Bước 2.3:")
    doc.add_paragraph("1. Truy cập trang 'Quản lý Đội hình' -> Click 'Tạo đội'.", style='List Number')
    doc.add_paragraph("2. Đặt tên đội thi đấu (Ví dụ: Đội bóng sông Hồng).", style='List Number')
    doc.add_paragraph("3. Trong danh sách chọn thành viên, hệ thống sẽ hiển thị danh sách đại biểu của đơn vị mình. Nếu môn đấu này đơn vị đã thiết lập liên quân active ở Bước 2.1, hệ thống hiển thị thêm danh sách đại biểu của các đơn vị đối tác liên quân để người dùng thoải mái ghép đội chung.", style='List Number')
    doc.add_paragraph("4. Chọn các thành viên, chỉ định vị trí thi đấu, số áo và đội trưởng, sau đó nhấn 'Lưu đội'.", style='List Number')
    
    # Section 3
    add_heading_styled(doc, "3. Hướng Dẫn Dành Cho Ban Nhân Sự HO & Admin", level=1)
    add_paragraph_styled(doc, "Nhân sự HO và Admin chịu trách nhiệm kiểm soát chất lượng dữ liệu, phê duyệt các yêu cầu đăng ký đại biểu từ đơn vị thành viên và thực hiện in thẻ hàng loạt phục vụ sự kiện.")
    
    add_heading_styled(doc, "Bước 3.1: Tiếp nhận và Phê duyệt/Từ chối đăng ký", level=2)
    add_paragraph_styled(doc, "Khi một đơn vị nhấn nút 'Nộp đăng ký', phiếu đăng ký chuyển trạng thái thành 'submitted' và khóa quyền chỉnh sửa của đơn vị. HR HO vào danh sách đăng ký:")
    add_bullet_item(doc, "Kiểm tra tính hợp lệ: ", "Xem danh sách đại biểu của đơn vị, click xem trước (preview) ảnh chân dung, ảnh CCCD trước/sau và scan Hợp đồng lao động để đảm bảo đúng người, đúng ảnh rõ nét.")
    add_bullet_item(doc, "Phê duyệt phiếu (Approve): ", "Nếu tất cả đại biểu hợp lệ, nhấn 'Phê duyệt'. Hệ thống sẽ tự động thực hiện 2 tác vụ ngầm: Sinh mã token QR Code ngẫu nhiên duy nhất (qr_token) và cấp số thứ tự thẻ (badge_number) tăng dần.")
    add_bullet_item(doc, "Từ chối phiếu (Reject): ", "Nếu phát hiện hồ sơ lỗi (VD: Ảnh mờ, hợp đồng lao động sai người...), HR nhấn 'Từ chối' và bắt buộc phải nhập lý do cụ thể. Phiếu đăng ký chuyển về trạng thái 'rejected', đơn vị sẽ nhận thông báo, chỉnh sửa lại hồ sơ và nộp lại.")
    
    add_callout(doc, "Lưu ý quy trình: Hệ thống chỉ hỗ trợ duyệt hoặc từ chối TOÀN BỘ phiếu đăng ký của đơn vị để đảm bảo tính đồng bộ dữ liệu, không hỗ trợ duyệt lẻ tẻ từng người.")
    
    add_heading_styled(doc, "Bước 3.2: Quản lý và in thẻ đại biểu hàng loạt (Badge Management)", level=2)
    add_paragraph_styled(doc, "Trang Badge Management cho phép Admin thiết kế mẫu thẻ và thực hiện in thẻ vật lý:")
    add_bullet_item(doc, "Lọc dữ liệu: ", "Admin có thể lọc đại biểu theo Đơn vị, Trạng thái phê duyệt, hoặc Trạng thái in (Đã in / Chưa in).")
    add_bullet_item(doc, "Kiểm tra mẫu thẻ (Preview): ", "Hiển thị ảnh thẻ đại biểu CR80 hoàn chỉnh với ảnh chân dung góc, họ tên, chức vụ, dải màu theo vai trò và mã QR Code liên kết đến trang cá nhân đại biểu.")
    add_bullet_item(doc, "Xuất bản in hàng loạt: ", "Hệ thống hỗ trợ xuất hàng loạt ảnh thẻ chất lượng cao (300 DPI, kích thước tiêu chuẩn 85.6x53.98mm = 1011x638px) dưới dạng file ZIP nén chứa tất cả ảnh PNG hoặc kết hợp thành file PDF nhiều trang để gửi trực tiếp cho nhà in.")
    
    add_centered_picture(doc, IMAGE_PATHS['badge'], "Giao diện quản lý thẻ đại biểu hàng loạt của Admin, preview thẻ CR80 và các hành động xuất file in ấn", width_in=5.8)
    
    # Section 4
    add_heading_styled(doc, "4. Hướng Dẫn Dành Cho Trưởng Đoàn (Team Lead)", level=1)
    add_paragraph_styled(doc, "Đại biểu được chỉ định vai trò Trưởng đoàn (is_team_lead = 1) sẽ có thêm quyền quản lý hoạt động hậu cần ăn uống của đoàn mình trong suốt đại hội nhằm tránh lãng phí suất ăn.")
    
    add_heading_styled(doc, "Quy trình Báo cắt suất ăn (Meal Cutoff):", level=2)
    add_bullet_item(doc, "1. Truy cập phân hệ: ", "Trưởng đoàn đăng nhập bằng tài khoản đại biểu được cấp và truy cập vào tab 'Quản lý Suất ăn'.")
    add_bullet_item(doc, "2. Xem danh sách bữa ăn: ", "Màn hình hiển thị danh sách các bữa ăn được tổ chức trong đại hội (Bữa sáng, trưa, tối) theo từng ngày diễn ra sự kiện.")
    add_bullet_item(doc, "3. Báo cắt ăn (Cutoff): ", "Mặc định hệ thống để trạng thái 'Có ăn' cho toàn đoàn. Trưởng đoàn tích chọn checkbox trước tên đại biểu trong đoàn muốn báo cắt ăn cho bữa ăn đó (báo cắt lẻ tẻ) hoặc nhấn 'Cắt ăn toàn đoàn' (bulk cutoff).")
    add_bullet_item(doc, "4. Ghi nhận lý do: ", "Nhập lý do cắt ăn (VD: Đi ăn ngoài, tự túc...) và nhấn 'Xác nhận'. Hệ thống sẽ tự động trừ suất ăn trong tổng số suất nhà bếp cần phục vụ.")
    
    add_callout(doc, "Quy định khóa sổ (Cutoff Deadline): Mỗi bữa ăn có quy định giờ khóa sổ (ví dụ: Bữa trưa khóa sổ lúc 9:00 sáng cùng ngày). Nếu Trưởng đoàn thao tác sau giờ khóa sổ, hệ thống sẽ hiện cảnh báo và chặn không cho báo cắt ăn.")
    
    # Section 5
    add_heading_styled(doc, "5. Hướng Dẫn Các Ban Tổ Chức Chuyên Môn", level=1)
    add_paragraph_styled(doc, "Hệ thống EventRegis hỗ trợ đắc lực cho các tiểu ban chuyên môn tự động hóa quy trình nghiệp vụ tổ chức trong suốt đại hội.")
    
    add_heading_styled(doc, "5.1 Ban Tổ Chức Thi Nghiệp Vụ", level=2)
    add_paragraph_styled(doc, "Quản lý các cuộc thi nghiệp vụ (ví dụ: Thi Lễ tân xuất sắc, Thi CSKH chuyên nghiệp):")
    add_bullet_item(doc, "Cấu hình phòng ban thi: ", "Để đảm bảo thí sinh có chuyên môn đúng lĩnh vực, BTC cấu hình giới hạn mã phòng ban tham gia (bảng competition_departments). Ví dụ: Cuộc thi Lễ tân xuất sắc chỉ cho phép phòng ban có mã 'LETAN', 'CSKH' đăng ký.")
    add_bullet_item(doc, "Cấp số báo danh (SBD) tự động: ", "Sau khi chốt danh sách, BTC nhấn nút 'Cấp SBD tự động'. Hệ thống tự động tạo mã số báo danh tăng dần dựa trên cấu hình tiền tố cuộc thi (prefix), số bắt đầu và độ rộng đệm. Ví dụ: Cuộc thi Lễ tân có prefix='LT', start=1, pad=3 -> LT001, LT002, LT003...")
    add_bullet_item(doc, "Xuất danh sách phòng thi: ", "BTC xuất danh sách thí sinh + SBD ra file Excel hoặc PDF để dán trước cửa phòng thi.")
    
    add_heading_styled(doc, "5.2 Ban Tổ Chức Thể Thao", level=2)
    add_paragraph_styled(doc, "Hỗ trợ quản lý lịch thi đấu thể thao đại hội:")
    add_bullet_item(doc, "Thiết lập giải đấu: ", "Tạo môn thể thao (theo cấu hình cha-con, ví dụ môn gốc 'Bóng đá' -> môn con 'Bóng đá nam', 'Bóng đá nữ') và tạo lịch thi đấu (chia bảng đấu vòng tròn tính điểm hoặc thi đấu loại trực tiếp - knockout).")
    add_bullet_item(doc, "Cập nhật tỉ số trực tiếp (Live Score): ", "Ngay tại sân thi đấu, BTC cập nhật kết quả trận đấu trên thiết bị di động. Hệ thống sẽ tự động tính toán bảng xếp hạng standings (đối với bảng đấu vòng tròn) hoặc cập nhật sơ đồ nhánh đấu knockout (bracket) hiển thị ra trang công cộng thời gian thực.")
    
    add_heading_styled(doc, "5.3 Ban Tổ Chức Tiệc & Phân chỗ ngồi", level=2)
    add_paragraph_styled(doc, "BTC Tiệc thiết lập vị trí sơ đồ bàn và gán chỗ ngồi trực quan trên đồ họa:")
    add_bullet_item(doc, "Thiết kế Canvas kéo thả: ", "Thiết lập sơ đồ không gian tiệc đại hội. BTC có thể kéo thả để định vị trí các bàn tiệc dạng hình tròn hoặc chữ nhật trên canvas. Phân loại bàn tiệc: Bàn VIP (burgundy đỏ nổi bật, vị trí gần sân khấu), Bàn thường (màu xanh navy).")
    add_bullet_item(doc, "Gán chỗ ngồi trực quan: ", "Click chọn một bàn tiệc -> Màn hình hiển thị danh sách 10 ghế. Kéo đại biểu từ danh sách 'Chưa phân chỗ' ở sidebar bên phải thả vào vị trí ghế mong muốn để xếp chỗ ngồi cụ thể.")
    
    add_centered_picture(doc, IMAGE_PATHS['banquet'], "Giao diện Canvas thiết lập sơ đồ bàn tiệc kéo thả, phân chia bàn VIP và bàn thường trực quan", width_in=5.8)
    
    # Section 6
    add_heading_styled(doc, "6. Hướng Dẫn Dành Cho Đại Biểu (Public QR Page)", level=1)
    add_paragraph_styled(doc, "Người tham dự đại hội không cần tài khoản đăng nhập để sử dụng tính năng này. Khi nhận được thẻ đại biểu vật lý, đại biểu chỉ cần dùng camera điện thoại quét mã QR Code in trên thẻ để truy cập nhanh Trang Landing Page di động cá nhân hóa:")
    
    add_bullet_item(doc, "Thẻ Đại biểu Điện tử: ", "Màn hình đầu trang hiển thị thẻ đại biểu điện tử đẹp mắt có ảnh chân dung, họ tên, chức vụ, đơn vị và dải màu vai trò tương thích với thẻ giấy.")
    add_bullet_item(doc, "Lịch trình Đại hội (Agenda): ", "Tra cứu toàn bộ chương trình, khung giờ, địa điểm diễn ra các phiên họp, lễ khai mạc/bế mạc và tiệc tối đại hội.")
    add_bullet_item(doc, "Lịch thi nghiệp vụ cá nhân: ", "Hiển thị chi tiết số báo danh (SBD), thời gian thi, phòng thi và kết quả thi nghiệp vụ của chính đại biểu.")
    add_bullet_item(doc, "Lịch thi đấu thể thao của Đơn vị: ", "Theo dõi các trận đấu sắp tới của đội thể thao đại diện cho đơn vị mình tham gia tranh tài (Thời gian, đối thủ, địa điểm thi đấu và tỉ số kết quả cập nhật live).")
    
    add_centered_picture(doc, IMAGE_PATHS['mobile'], "Giao diện di động QR Landing Page của Đại biểu hiển thị thẻ điện tử, agenda cá nhân hóa và kết quả thi đấu", width_in=3.5)
    
    # Save the document
    out_path = r'e:\eventregis\docs\word\Huong_dan_su_dung_EventRegis.docx'
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    doc.save(out_path)
    print(f"User guide generated and saved successfully to {out_path}")

if __name__ == '__main__':
    generate_docx()
